DeviceAsWebcam
Universal-Debloater-Alliance/universal-android-debloater-next-generation pull request #145
Opened 2024-01-01 08:39 UTC by JoshAtticus

Pixel 8/8 Pro exclusive feature

2024-01-01 13:52 UTC, Blitz517 commented
"com.google.android.apps.diagnosticstool" may be recommended?

2024-01-01 14:32 UTC, JoshAtticus commented
> "com.google.android.apps.diagnosticstool" may be recommended?

Removing it breaks repair mode as well so probably not

2024-01-01 20:24 UTC, AnonymousWP requested changes

2024-01-01 20:24 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "id": "com.android.DeviceAsWebcam",
Are you sure it's with capital letters?

2024-01-01 20:24 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "description": "Allows using certain Pixel phones as a USB webcam.\n Will break USB function picker.",
```suggestion
    "description": "Allows using certain Pixel phones as a USB webcam.\nWill break USB function picker.",
```
Remove redundant space.

2024-01-01 20:24 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "description": "Google Pixel diagnostics tool.\n Exclusive to Pixel Watch 1 & 2 along with Pixel 6 series and later running Wear OS 4/Android 14.",
```suggestion
    "description": "Google Pixel diagnostics tool.\nExclusive to Pixel Watch 1 & 2 along with Pixel 6 series and later running Wear OS 4/Android 14.",
```
Remove redundant space.

2024-01-01 20:24 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "description": "Google Pixel AI wallpaper.\n Exclusive to Pixel 6 series and later running Android 14.",
```suggestion
    "description": "Google Pixel AI wallpaper.\n Exclusive to Pixel 6 series and later running Android 14.",
```
Remove redundant space.

2024-01-26 15:02 UTC, AnonymousWP commented
@JoshAtticus Please follow-up on the above.

2024-01-27 01:28 UTC, JoshAtticus commented on resources/assets/uad_lists.json
> +    "id": "com.android.DeviceAsWebcam",
Yes it is

2024-01-29 08:48 UTC, AnonymousWP commented
> > @JoshAtticus Please follow-up on the above.
> 
> It won't let me commit any of the changes because the diff has changed or whatever

In that case, just make the changes I suggested and push to your fork/branch so it's included in this PR.

2024-01-31 02:45 UTC, closed without merging

2024-01-31 07:03 UTC, AnonymousWP commented
Why did you close this PR??

2024-01-31 10:35 UTC, JoshAtticus commented
> Why did you close this PR??

I don't know how to do that stuff

2024-01-31 11:35 UTC, AnonymousWP commented
@Blitz517 Could you please add some Pixel/OASP packages from this current PR but via a new PR?

2024-02-01 06:22 UTC, JoshAtticus commented
> @AnonymousWP these apps looks like a from android 14, I will check if its possible

Yes, they are from Android 14