Removed all recommendations of Simple apps. Fixes #158
Universal-Debloater-Alliance/universal-android-debloater-next-generation pull request #161
Opened 2024-01-07 05:12 UTC by Frigyes06

2024-01-07 11:33 UTC, AnonymousWP requested changes

2024-01-07 11:33 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "description": "Swiftkey Keyboard (https://play.google.com/store/apps/details?id=com.touchtype.swiftkey)\nKeyboard app by TouchType, a Microsoft subsidiary (https://en.wikipedia.org/wiki/SwiftKey
```suggestion
    "description": "Swiftkey Keyboard (https://play.google.com/store/apps/details?id=com.touchtype.swiftkey)\nKeyboard app by TouchType, a Microsoft subsidiary (https://en.wikipedia.org/wiki/SwiftKey)\n4 Trackers + 11 Permissions: https://reports.exodus-privacy.eu.org/en/reports/com.touchtype.swiftkey/latest/\nNOTE: default keyboard on some Nokia and Huawei phones. Make sure you have another keyboard app before disabling this.\nOpenBoard is FOSS, based on the AOSP keyboard and has direct boot support:\nhttps://f-droid.org/packages/org.dslul.openboard.inputmethod.latin/",
```

2024-01-12 09:09 UTC, yjhn requested changes
Simple Keyboard (https://f-droid.org/packages/rkr.simplekeyboard.inputmethod/, https://github.com/rkkr/simple-keyboard) is unrelated to Simple Mobile Tools.

So its recommendations shouldn't be removed.

2024-01-12 12:40 UTC, adhirajsinghchauhan commented on resources/assets/uad_lists.json
> +    "description": "Swiftkey Keyboard (https://play.google.com/store/apps/details?id=com.touchtype.swiftkey)\nKeyboard app by TouchType, a Microsoft subsidiary (https://en.wikipedia.org/wiki/SwiftKey
Commit suggestions not working is a known GitHub bug. I've done it manually in 6271e0068f8b772e98543cc64ef442c8e2c42192 for all occurrences.

2024-01-15 23:31 UTC, AnonymousWP commented
> [yjhn](/yjhn)

But the name is the same, I believe. How would users know the difference? Both are in the Play Store. I've linked to the Google Play Store one in the descriptions. At the same time, I feel like we shouldn't be in the position to recommend applications. It's mostly subjective, so I'm not a fan of advertising apps in the description like "choose app X, because of reason Y and Z!".

2024-01-22 09:07 UTC, yjhn commented
> At the same time, I feel like we shouldn't be in the position to recommend applications. It's mostly subjective, so I'm not a fan of advertising apps in the description like "choose app X, because of reason Y and Z!".

I mostly agree (although there is the issue of discoverability). But if we decide to not recommend specific apps, all app recommendations should be removed.

2024-01-22 09:15 UTC, yjhn reviewed
Still need to decide on whether to recommend specific alternative apps, but it can wait.

2024-01-22 09:15 UTC, yjhn commented on resources/assets/uad_lists.json
> +    "description": "Swiftkey Keyboard (https://play.google.com/store/apps/details?id=com.touchtype.swiftkey)\nKeyboard app by TouchType, a Microsoft subsidiary (https://en.wikipedia.org/wiki/SwiftKey
> and has direct boot support

Maybe it should say something like "can be used as lockscreen keyboard" (assuming I understood [direct boot mode](https://developer.android.com/privacy-and-security/direct-boot) correctly from a cursory glance)?

2024-01-22 19:51 UTC, AnonymousWP commented
> > At the same time, I feel like we shouldn't be in the position to recommend applications. It's mostly subjective, so I'm not a fan of advertising apps in the description like "choose app X, because of reason Y and Z!".
> 
> I mostly agree (although there is the issue of discoverability). But if we decide to not recommend specific apps, all app recommendations should be removed.

Correct, but that's *a lot* of work probably. Haven't checked how many entries there are though.

> Still need to decide on whether to recommend specific alternative apps, but it can wait.

Internally we already decided to not recommend specific alternative apps. We'll not allow it for future PRs/commits, but removing is probably a lot of work. We'll see what we can do. Others are also free to file PRs of course.

2024-01-26 14:49 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "description": "Swiftkey Keyboard (https://play.google.com/store/apps/details?id=com.touchtype.swiftkey)\nKeyboard app by TouchType, a Microsoft subsidiary (https://en.wikipedia.org/wiki/SwiftKey
No, sorry, because then I'll have to explain which apps also support direct boot mode.

2024-01-26 14:56 UTC, AnonymousWP approved these changes

2024-01-26 14:57 UTC, merged