refactor: remove unused string inside enum variants
Universal-Debloater-Alliance/universal-android-debloater-next-generation pull request #165
Opened 2024-01-08 11:01 UTC by lavafroth

### Changes
- Removes unused `String` from `LoadingState` variants that never use the inner string
- Use the derive macro to specify the default value instead of manual implementation

2024-01-08 12:43 UTC, adhirajsinghchauhan commented
I would be better to merge all refactor changes to a single PR. These are mostly style/lint changes, so can be grouped together (separate commits though).

2024-01-09 04:02 UTC, lavafroth commented
@adhirajsinghchauhan I'm refraining from massive PRs to make sure I'm not making unintended changes. I have a few more performance improvements and I want some sanity check before merging things right away.

2024-01-09 07:30 UTC, adhirajsinghchauhan requested changes

2024-01-09 07:30 UTC, adhirajsinghchauhan commented on src/gui/views/list.rs
> +                waiting_view(settings, "Finding connected devices...", true)
This should not be `true`. The "No internet" button is meant to be shown only for `DownloadingList`.

2024-01-09 07:30 UTC, adhirajsinghchauhan commented on src/gui/views/list.rs
> +                waiting_view(settings, text, true)
This should not be `true`

2024-01-09 07:30 UTC, adhirajsinghchauhan commented on src/gui/views/list.rs
> +                waiting_view(settings, "Updating UAD-ng. Please wait...", true)
This should not be `true`

2024-01-09 07:30 UTC, adhirajsinghchauhan commented on src/gui/views/list.rs
> +                waiting_view(settings, &format!("Restoring device: {device}"), true)
This should not be `true`

2024-01-10 06:53 UTC, adhirajsinghchauhan approved these changes

2024-01-10 06:54 UTC, merged