update some samsung pkgs
Universal-Debloater-Alliance/universal-android-debloater-next-generation pull request #192
Opened 2024-01-27 14:44 UTC by prakharb5

2024-01-31 22:50 UTC, AnonymousWP requested changes

2024-01-31 22:50 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "description": "Samsung Quick connect (discontinued?)\nIn theory, it lets you connect your phone to a variety of devices over Wifi that support\nmultiple protocols — including Wifi Direct and Mir
```suggestion
    "description": "Samsung Quick connect (discontinued?)\nIn theory, it lets you connect your phone to a variety of devices over Wifi that support multiple protocols — including Wifi Direct and Miracast — to display photos, video or audio.\nhttps://www.samsung.com/uk/support/tv-audio-video/what-is-screen-mirroring-and-how-do-i-use-it-with-my-samsung-tv-and-samsung-mobile-device/\n",
```
See edit. May I ask why you wanted to add an extra whiteline in the middle of the sentence?

2024-01-31 22:50 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "description": "Samsung Smart Call\nProvides caller profile information to help consumers identify incoming calls and block unwanted ones.\nAlso related to the 'local places' feature in Samsung d
```suggestion
    "description": "Samsung Smart Call\nProvides caller profile information to help consumers identify incoming calls and block unwanted ones.\nAlso related to the 'local places' feature in Samsung dialer.\nRelies on Hiya (see com.hiya.star)\nTL;DR: really bad for your privacy.",
```

2024-01-31 22:50 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "description": "My Profile\n\nRelated to Samsung Members?\n",
```suggestion
    "description": "My Profile\nRelated to Samsung Members?",
```
No need for a double whiteline here. Single is enough (just like everywhere else).

2024-01-31 22:50 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "description": "Safety information telling you not to put your phone in your eyes or other dangerous stuff\n",
```suggestion
    "description": "Safety information telling you not to put your phone in your eyes or other dangerous stuff\n",
```
This kind of sounds weird. You don't put your phone *in* your eyes. Does it really say that?😅

2024-01-31 22:50 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "description": "HwModuleTest, a hardware hidden test app (dial *#0*# to open it).\nHas stuff to quickly check the phone hardware. Removing it does not break anything, but no point in removing it.
```suggestion
    "description": "HwModuleTest, a hardware hidden test app (dial *#0*# to open it).\nHas stuff to quickly check the phone's hardware. Removing it does not break anything, but no point in removing it.",
```

2024-01-31 22:50 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "description": "Samsung Location SDK\nI just know this doesn't have any impact on GPS stuff. \nIt seems to be only used along samsung apps.\n",
```suggestion
    "description": "Samsung Location SDK\nI just know this doesn't have any impact on GPS stuff.\nIt seems to be only used along Samsung apps.\n",
```

2024-02-05 18:38 UTC, prakharb5 commented on resources/assets/uad_lists.json
> +    "description": "Safety information telling you not to put your phone in your eyes or other dangerous stuff\n",
I haven't opened the app myself, so no clue about that. I feel it would the old regular legal stuff, so I won't be surprised if it actually has that exact statement.

2024-02-05 18:40 UTC, prakharb5 commented on resources/assets/uad_lists.json
> +    "description": "Samsung Quick connect (discontinued?)\nIn theory, it lets you connect your phone to a variety of devices over Wifi that support\nmultiple protocols — including Wifi Direct and Mir
This is so that, if the user opens the app window too wide, the text wouldn't be hard to read by having to turn your neck again and again.
More towards accessibility.

2024-02-06 19:57 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "description": "Samsung Quick connect (discontinued?)\nIn theory, it lets you connect your phone to a variety of devices over Wifi that support\nmultiple protocols — including Wifi Direct and Mir
I don't think it's needed, as it's displayed fine for most other packages as well. Please commit the suggestion.

2024-02-06 19:58 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "description": "Safety information telling you not to put your phone in your eyes or other dangerous stuff\n",
Hmm, honestly no idea what we should put. What Samsung says makes no sense to me.

2024-02-08 14:56 UTC, prakharb5 commented on resources/assets/uad_lists.json
> +    "description": "Safety information telling you not to put your phone in your eyes or other dangerous stuff\n",
I just made a change. Have a look.

2024-02-08 15:07 UTC, AnonymousWP requested changes

2024-02-08 15:07 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "description": "Safety information telling you not to put your phone in your eyes or other dangerous stuff\n",
Add "your phone" instead of just "phone".

2024-02-11 02:42 UTC, prakharb5 commented on resources/assets/uad_lists.json
> +    "description": "Safety information telling you not to put your phone in your eyes or other dangerous stuff\n",
Done

2024-02-11 11:55 UTC, AnonymousWP approved these changes

2024-02-11 11:55 UTC, merged