fix: allow the app to display logs when launced from the terminal on windows
Universal-Debloater-Alliance/universal-android-debloater-next-generation pull request #238
Opened 2024-02-10 13:54 UTC by B0ney

fixes: #237

2024-02-10 15:01 UTC, lavafroth requested changes
Could you please update your branch with the main branch? Also, you could possibly look into [this crate](https://docs.rs/win32console/latest/win32console/console/struct.WinConsole.html#method.attach_console).

2024-02-10 15:03 UTC, lavafroth commented
I'm unable to test this right now due to the lack of a windows machine @adhirajsinghchauhan, could you test these changes?

2024-02-10 15:59 UTC, B0ney commented
Done!

`win32console` does the job. My only complaint is that it doesn't seem to provide a `ATTACH_PARENT_PROCESS` constant or something equivalent.

2024-02-10 15:59 UTC, Frigyes06 commented
I can test later today

2024-02-11 05:29 UTC, lavafroth submitted a review, later dismissed
LGTM

2024-02-11 05:44 UTC, lavafroth approved these changes
The unsuccessful CI runs are due to a linting issue from a previous PR. Thanks a lot again!

2024-02-12 08:17 UTC, merged