Motorola more apps and better descriptions.
Universal-Debloater-Alliance/universal-android-debloater-next-generation pull request #252
Opened 2024-02-13 12:16 UTC by Blitz517

2024-02-13 21:35 UTC, AnonymousWP requested changes
I left some questions and suggestions. Please reply all of them via GitHub.

2024-02-13 21:35 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "description": "This app has permissions descriptions, lab, game mode launch permissions, audio monitor descriptions.\nSo it's permissions to system apps? It's in almost debloat lists to remove i
Sorry, but I don't know what you mean with "It's in almost debloat lists to remove it".

2024-02-13 21:35 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "description": "Virtual UICC Payment\nSIM Card Payment also NFC. Useful only in China.\nUICC stands for Universal Integrated Circuit Card.\nIt is a the physical and logical platform for the USIM
How have you verified it's only used in China?

2024-02-13 21:35 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "removal": "Advanced"
```suggestion
    "removal": "Expert"
```
If the implications are unknown and it's related to settings, maybe it should be expert instead. "Random settings" is too vague.

2024-02-13 21:35 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "removal": "Recommended"
If it's by the carrier, wouldn't this break software updates then? Usually, carrier phones can only update via that one built-in updater.

2024-02-13 21:35 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "description": "Overlay to Android System Intelligence 'com.google.android.as', not needed.",
It's not needed for Android System Intelligence?

2024-02-13 21:35 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "description": "Overlay to 'com.motorola.motointelligence', not needed.",
Not needed for com.motorola.motointelligence to work correctly or?

2024-02-13 21:35 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "description": "Moto Lights\nPeople recommend to remove it.",
Why do they recommend to remove it and what is it for?

2024-02-13 21:35 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "removal": "Recommended"
```suggestion
    "removal": "Advanced"
```
This is a feature for spatial sound. Removing this will break it, so it shouldn't be `Recommended`.

2024-02-13 21:35 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "removal": "Recommended"
```suggestion
    "removal": "Advanced"
```
If you're not sure, then why using `Recommended`?

2024-02-13 21:35 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "removal": "Recommended"
```suggestion
    "removal": "Recommended"
```
This is an important aspect of the system. Why did you make it `Recommended`??

2024-02-13 21:49 UTC, Blitz517 commented on resources/assets/uad_lists.json
> +    "description": "Invisible net\nApp for Alias ID, Shortcut Installer(random apps, almost china.)\nIt's some kind of a stub application launcher, if you open any of it's activities it goes to the p
Most of the apps I have seen are Chinese apps

2024-02-13 21:50 UTC, Blitz517 commented on resources/assets/uad_lists.json
> +    "description": "Virtual UICC Payment\nSIM Card Payment also NFC. Useful only in China.\nUICC stands for Universal Integrated Circuit Card.\nIt is a the physical and logical platform for the USIM
by hidden image files

2024-02-13 21:52 UTC, Blitz517 commented on resources/assets/uad_lists.json
> +    "description": "This app has permissions descriptions, lab, game mode launch permissions, audio monitor descriptions.\nSo it's permissions to system apps? It's in almost debloat lists to remove i
"com.motorola.motosignature.app" google search shows that its on some lists that recommend removing this app

2024-02-13 21:54 UTC, Blitz517 commented on resources/assets/uad_lists.json
> +    "removal": "Advanced"
this app is safe to remove so better keep it in advanced?

2024-02-13 21:55 UTC, Blitz517 commented on resources/assets/uad_lists.json
> +    "removal": "Advanced"
if someone who first wrote this description, really remove this app

2024-02-13 21:58 UTC, Blitz517 commented on resources/assets/uad_lists.json
> +    "removal": "Recommended"
it has some words like 'Downloading system update', 'veryfying update...' weird thing is why theres random words about AT&T Software Update or Cricket Software update,
my guess NOW is this name of app is just a 'Software Update'
so its my mistake

2024-02-13 22:01 UTC, Blitz517 commented on resources/assets/uad_lists.json
> +    "description": "Overlay to Android System Intelligence 'com.google.android.as', not needed.",
it sets this app to default system captions, default app prediction service, system audio intelligence, config systemui intelligence. Maybe its needed, maybe not. more extended name to it is: com.google.android.apps.miphone.aiai.app.AiAiPredictionService
its recommended to remove it so?

2024-02-13 22:03 UTC, Blitz517 commented on resources/assets/uad_lists.json
> +    "description": "Overlay to 'com.motorola.motointelligence', not needed.",
weird thing is a this rom when i check, the app "com.motorola.motointelligence" probably not exist?!

2024-02-13 22:03 UTC, Blitz517 commented on resources/assets/uad_lists.json
> +    "description": "Overlay to 'com.motorola.motointelligence', not needed.",
also in uad_lists this app is not listed

2024-02-13 22:10 UTC, Blitz517 commented on resources/assets/uad_lists.json
> +    "removal": "Recommended"
um hard to say, code is too small, no activities only some frameworks in classes.dex

2024-02-13 22:13 UTC, Blitz517 commented on resources/assets/uad_lists.json
> +    "removal": "Recommended"
Also it has something to background updates? It should be Advanced '-'

2024-02-13 22:19 UTC, Blitz517 commented on resources/assets/uad_lists.json
> +    "removal": "Recommended"
This app does not look very useful, not all moto have this app than just some. This app notifies you when the phone is too hot or turns off it, no more stuff.

2024-02-13 22:33 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "description": "Invisible net\nApp for Alias ID, Shortcut Installer(random apps, almost china.)\nIt's some kind of a stub application launcher, if you open any of it's activities it goes to the p
Could you please reflect that in the description?

2024-02-13 22:33 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "description": "This app has permissions descriptions, lab, game mode launch permissions, audio monitor descriptions.\nSo it's permissions to system apps? It's in almost debloat lists to remove i
Ah alright, please clearly tell that in the description.

2024-02-13 22:33 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "description": "Virtual UICC Payment\nSIM Card Payment also NFC. Useful only in China.\nUICC stands for Universal Integrated Circuit Card.\nIt is a the physical and logical platform for the USIM
Then please mention that in the description.

2024-02-13 22:35 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "removal": "Advanced"
But settings can be a vital part of the system, which is what `Expert` is for.

2024-02-13 22:35 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "removal": "Recommended"
Yeah, so can you change the removal to `Expert`?

2024-02-13 22:38 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "description": "Overlay to Android System Intelligence 'com.google.android.as', not needed.",
If it's directly related to Android System Intelligence and removal means you can't use system captions and so, then make it `Advanced` please.

2024-02-13 22:43 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "description": "Overlay to 'com.motorola.motointelligence', not needed.",
I see, but it doesn't break anything? Kind of tricky to use `Recommended` if you're not sure. Maybe make it `Advanced` instead.

2024-02-13 22:44 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "description": "Moto Lights\nPeople recommend to remove it.",
Yeah, so this definitely not be `Recommended`. Please change it to `Advanced` and adjust the description to be more detailed.

2024-02-13 22:46 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "removal": "Recommended"
Just make it `Advanced` to be sure (you can commit my suggestion). If people want to, they can still uninstall/disable it.

2024-02-13 22:47 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "removal": "Recommended"
Yes, so please commit my suggestion.
![image](https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/assets/50231698/8a852f75-0cc7-4424-8d77-b1b821b2aa27)

2024-02-13 22:47 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "removal": "Recommended"
Yes that's considered a vital part of the system actually. If this does not happen, your phone can explode or catch fire. This should be `Expert`.

2024-02-14 17:30 UTC, AnonymousWP submitted a review, later dismissed
Looks good to me now. Remember to use the "Commit suggestion" feature. That also means less work for you. 😉

2024-02-14 17:33 UTC, AnonymousWP approved these changes

2024-02-14 17:34 UTC, merged