OPPO more packages
Universal-Debloater-Alliance/universal-android-debloater-next-generation pull request #253
Opened 2024-02-13 12:43 UTC by Blitz517

2024-02-18 12:34 UTC, AnonymousWP requested changes
Thanks again for this big PR. I left some comments and made some suggestions. Please check them carefully.

2024-02-18 12:34 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "id": "com.oplus.battery",
According to https://xdaforums.com/t/how-to-fix-oneplus-11-thermal-throttling.4560085/post-89255314, `com.oplus.battery` isn't directly related to the battery (firmware) itself.

> Hi guys, what are the side effects of disabling com.oplus.battery? Does the app control other things? I'm worried that disabling it can remove all the smart optimization for the battery and make it discharge faster, even in condition of low stress, am i wrong? Someone that have done it can tell me if disabling it lead to lose other function? Thank you very much.

> Nothing is affected all works fine, you just can't optimise apps after disabling battery app.

What do you think of `Expert` instead?

2024-02-18 12:34 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "description": "Battery\nNeeded for power managment in settings.",
See above. Description will have to be edited too.

2024-02-18 12:34 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "removal": "Advanced"
```suggestion
    "removal": "Recommended"
```
If removing this doesn't break anything, then why not `Recommended`? Or does it have dependencies?

2024-02-18 12:34 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "description": "Carrier settings update?\nLooks like a more Software Updates.",
```suggestion
    "description": "Carrier software updater?\nLooks like software updater for carrier phones.",
```

2024-02-18 12:34 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "description": "Engineermode2\nShows Sar IMEI.",
Maybe also related to FlipKart? See package name.

2024-02-18 12:34 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "description": "DSF\nNeeded for account only?",
Can't find much about it to be honest. Is this everything you can find about it?

2024-02-18 12:34 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "description": "FIDO UAF1.0 ASM\nRelated to app fingerprint unlocking and payments. Safe to remove if you don't use password-less authentification to access online services.\n'com.fido.asm' is th
```suggestion
    "description": "FIDO UAF1.0 ASM\nRelated to app fingerprint unlocking and payments. Safe to remove if you don't use passwordless authentication to access online services.\n'com.fido.asm' is the same app.",
```

2024-02-18 12:34 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "removal": "Recommended"
```suggestion
    "removal": "Advanced"
```
Don't you think this should be `Advanced` instead? Because this app has more permissions than other regular apps from the Play Store in order to make complete back-ups. I could be wrong though.

2024-02-18 12:34 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "description": "Music Party\nIts app that allows you to play music.",
```suggestion
    "description": "Music Party\nThis app allows you to play music through different phones, synchronised.\nhttps://www.youtube.com/watch?v=3Ak222Z79RY",
```

2024-02-18 12:34 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "description": "Notification managment will not work.",
```suggestion
    "description": "Notification management will not work when uninstalled/disabled.",
```

2024-02-18 12:34 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "description": "Gesture_Motion Services\nIs related to gesture navigation 'com.oplus.gesture'.",
```suggestion
    "description": "Gesture Motion Services\nIs related to gesture navigation 'com.oplus.gesture'.",
```

2024-02-18 12:34 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "removal": "Recommended"
```suggestion
    "removal": "Expert"
```
If it's directly related to that gesture package, then it should break gestures entirely as well I think. Therefore I think `Expert` makes more sense.

2024-02-18 12:34 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "removal": "Recommended"
```suggestion
    "removal": "Expert"
```

2024-02-18 12:34 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "description": "OPPO Launcher",
```suggestion
    "description": "OPPO Launcher\nCan be disabled when using another launcher.",
```
Agreed?

2024-02-18 12:34 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "description": "It's probably virtual communications.\nAlso about these it's in the code.",
What does this mean? Virtual communications. Isn't that important then?

2024-02-18 12:34 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "description": "Its app for virtual communication. Depends on 'com.oplus.virtualcomm'.",
What does this mean? Virtual communications. Isn't that important then?

2024-02-18 12:34 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "removal": "Recommended"
```suggestion
    "removal": "Advanced"
```
Some people may want to use it, so I think `Advanced` should make more sense.

2024-02-18 13:52 UTC, Blitz517 commented on resources/assets/uad_lists.json
> +    "id": "com.oplus.battery",
I think to better give a link to this xda forum and from unsafe to expert for people to test it.

2024-02-18 13:54 UTC, Blitz517 commented on resources/assets/uad_lists.json
> +    "removal": "Advanced"
I set it to advanced because there's no trackers or ads, like a stock aosp app.

2024-02-18 14:02 UTC, Blitz517 commented on resources/assets/uad_lists.json
> +    "description": "Engineermode2\nShows Sar IMEI.",
Its for get flipkartAddress and ShowSarImeiReceiver
<string name="sar_and_imei_value">Head SAR: %1$s W/kg
Body SAR: %2$s W/kg
%3$s
This phone is part of Flipkart Smart Plan and not eligible for release till any instant advance amount availed is repaid. Visit %4$s for more information</string>

2024-02-18 14:03 UTC, Blitz517 commented on resources/assets/uad_lists.json
> +    "description": "Engineermode2\nShows Sar IMEI.",
and theres random big text about Flipkart ^^^

2024-02-18 14:06 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "id": "com.oplus.battery",
Yes, sure, please do that.

2024-02-18 14:08 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "removal": "Advanced"
Fair enough.

2024-02-18 14:08 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "description": "Engineermode2\nShows Sar IMEI.",
Do you think this is worth mentioning extra in the description field?

2024-02-18 14:10 UTC, Blitz517 commented on resources/assets/uad_lists.json
> +    "description": "DSF\nNeeded for account only?",
to say more things i found this site https://4pda.to/forum/index.php?showtopic=1028146&st=1320
translated to english:
"Device Connection Security Service" provides the ability to authenticate your identity when you connect your device. For the "Device Connection Security Service" to work properly, it needs to collect information about your HeyTap account to support automatic connection to different devices with the same account and connect to the Internet to verify the security of your HeyTap account. If you don't want to use the "Security Service for connecting devices", you can turn it off under "Settings - Advanced Settings - Optimization Services". Once the service is turned off, devices associated with one account will no longer connect automatically.
Also I found they get this info from string name="summary" >
so its needed for Device Connection Security Service (useful when using heytap account probably?)

2024-02-18 14:19 UTC, Blitz517 commented on resources/assets/uad_lists.json
> +    "removal": "Recommended"
uninstallable system app recovery to advanced? it may be ok to set advanced when no trackers, ads, but never seen it on other phones

2024-02-18 14:29 UTC, Blitz517 commented on resources/assets/uad_lists.json
> +    "description": "OPPO Launcher",
probably not https://github.com/0x192/universal-android-debloater/issues/972

2024-02-18 14:30 UTC, Blitz517 commented on resources/assets/uad_lists.json
> +    "removal": "Recommended"
maybe advanced?

2024-02-18 14:30 UTC, Blitz517 commented on resources/assets/uad_lists.json
> +    "removal": "Recommended"
advanced?

2024-02-18 14:40 UTC, Blitz517 commented on resources/assets/uad_lists.json
> +    "description": "It's probably virtual communications.\nAlso about these it's in the code.",
idk men this app has no activities, no permissions, only some code in classes.dex theres dmtp client things and virtualcomm

2024-02-18 14:44 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "description": "DSF\nNeeded for account only?",
Ah okay, I see. Could you reflect this in the description (only most important parts)?

2024-02-18 14:46 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "removal": "Recommended"
I'm not sure if it has no trackers or ads, but I don't think it's "upright pointless".

2024-02-18 14:46 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "removal": "Recommended"
No, why? Gestures are a vital and widespread part of the system.

2024-02-18 14:46 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "removal": "Recommended"
No, why? Gestures are a vital and widespread part of the system.

2024-02-18 14:47 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "description": "OPPO Launcher",
Ah I see, okay thanks.

2024-02-18 14:51 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "description": "It's probably virtual communications.\nAlso about these it's in the code.",
If we're not sure, I think you should change it to `Advanced`.

2024-02-18 15:25 UTC, Blitz517 commented on resources/assets/uad_lists.json
> +    "description": "Engineermode2\nShows Sar IMEI.",
yes

2024-02-18 15:25 UTC, Blitz517 commented on resources/assets/uad_lists.json
> +    "description": "DSF\nNeeded for account only?",
i will do more short description for that

2024-02-18 16:05 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "description": "Engineermode2\nShows Sar IMEI.",
Alright, with the next commit, please include it (including all other suggestions we agreed upon).

2024-02-19 09:07 UTC, AnonymousWP commented
Superseded & resolved by https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/pull/273.

2024-02-19 09:07 UTC, closed without merging