Pixel android 14 new packages
Universal-Debloater-Alliance/universal-android-debloater-next-generation pull request #254
Opened 2024-02-13 12:49 UTC by Blitz517

2024-02-18 13:01 UTC, AnonymousWP requested changes
See comments and suggestions.

2024-02-18 14:56 UTC, Blitz517 commented on resources/assets/uad_lists.json
> +    "description": "Sharing location to carrier.",
hm its carrier location, not any emergency stuff, but resources.arsc cant open normally, i found something about this: https://support.google.com/pixelphone?p=carrier_location_permissions
maybe it should be ``expert`` set

2024-02-18 15:04 UTC, Blitz517 commented on resources/assets/uad_lists.json
> +    "description": "Needed for VoLTE? Has a lot statistics and takes info about device.",
this app requires gms, has call notification but maybe theres no stuff about volte, maybe remove this ``Needed for VoLTE?`` this app is on some websites on the list degoogling.

2024-02-18 15:10 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "description": "Needed for VoLTE? Has a lot statistics and takes info about device.",
Yes sure, go ahead, but should this still be `Recommended` then? I don't think so, as we're still not sure about its implications.

2024-02-19 09:07 UTC, AnonymousWP commented
Superseded & resolved by https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/pull/273.

2024-02-19 09:07 UTC, closed without merging