feat(CI): changed release notes to use github's auto generated one.
Universal-Debloater-Alliance/universal-android-debloater-next-generation pull request #275
Opened 2024-02-19 22:23 UTC by Frigyes06

Fixes #218

2024-02-20 08:10 UTC, adhirajsinghchauhan requested changes
> Fixes #218

No, it does not.

My comment on `workflow_dispatch` makes it clear that there's still some confusion. We've yet to decide on the approach for releases: manual via GitHub frontend or automatically via this action (pushing semver to `main`).

2024-02-20 14:07 UTC, Frigyes06 commented on .github/workflows/release.yml
> +        uses: softprops/action-gh-release@v0.1.15
Huh that's weird. GH marketplace points to  v0.1.15 as the latest...

2024-02-20 14:10 UTC, Frigyes06 commented on .github/workflows/release.yml
> +  workflow_dispatch:
It still runs on tag push. I wanted to introduce workflow dispatch so we can re-trigger it on a tag to rule out one-time anomalies in github's runner system when debugging CI.
It would also make it easier to test the CI script on a non-release tag so we don't have to constantly push tags just to see the action run.

2024-02-20 14:11 UTC, Frigyes06 commented
> 
> No, it does not.
> 


You must have missed the part where it changes how the changelog is generated to use github's generator instead of copy-pasting the changelog.
Please review the changes thoroughly.

2024-02-20 14:22 UTC, Frigyes06 commented
>
> The "Fixes" keyword would auto-close the issue when this PR is merged, which is not what we want. This PR only partially addresses the entire issue; there are many other things we need to do to resolve (see comments there).
> 

It fixes what the body of the issue states, however I recognise valuable discussion in the comments.
Would opening a new issue to exclusively track the changelog issue and linking this PR to that be acceptable?
Then we could repurpose old issue for general CI changes tracking

2024-02-20 14:32 UTC, adhirajsinghchauhan commented on .github/workflows/release.yml
> +  workflow_dispatch:
This workflow doesn't need to be tested — it either works or it doesn't. Executing this will always create a release, and we certainly don't want to annoy watchers just for testing purposes (they get notified for every release by default).

2024-02-20 14:35 UTC, adhirajsinghchauhan commented
> Would opening a new issue to exclusively track the changelog issue and linking this PR to that be acceptable?

That would be great, yes. @AnonymousWP can create an issue to track checklist doc work, and for now we developers can create one just for what this PR aims to fix.

2024-02-20 14:36 UTC, adhirajsinghchauhan commented on .github/workflows/release.yml
> +  workflow_dispatch:
I'd advise reverting this; it is indeed out of scope. We can do it in another one.

2024-02-20 14:41 UTC, Frigyes06 commented on .github/workflows/release.yml
> +  workflow_dispatch:
> This workflow doesn't need to be tested — it either works or it doesn't. Executing this will always create a release, and we certainly don't want to annoy watchers just for testing purposes (they get notified for every release by default).

But when it doesn't work, we want to be able to test it so it will work next time around, without creating a bunch of releases. We could easily conditional set pre-releases which don't ping watchers. Will implement that in another PR, reverting in this temporarily

2024-02-21 07:47 UTC, adhirajsinghchauhan approved these changes

2024-02-21 07:48 UTC, merged