release(changelog): add and remove labels
Universal-Debloater-Alliance/universal-android-debloater-next-generation pull request #311
Opened 2024-03-02 20:28 UTC by AnonymousWP

A refactor doesn't always fix a bug, but a refactor does always change the code. However, changing code doesn't mean its function will change. Feature label doesn't exist, so replaced it by enhancement.

2024-03-03 03:22 UTC, lavafroth submitted a review, later dismissed

2024-03-03 03:25 UTC, adhirajsinghchauhan requested changes

2024-03-03 03:25 UTC, adhirajsinghchauhan commented on .github/release.yml
> +        - refactor
"Changed" is used less for code change and more for behaviour change — from the user's perspective — because release notes are more for users.

A refactor is always about the code itself, and should never change behaviour (assuming good practices). I don't think we should use that as a label for "Changed".

Instead, we should make a separate category for refactors. I tend to put them (amongst other non user-facing changes) into "Miscellaneous".

2024-03-03 12:44 UTC, AnonymousWP commented on .github/release.yml
> +        - refactor
Hmm, fair. I was thinking about it from a Conventional Commits kind of way: https://gist.github.com/qoomon/5dfcdf8eec66a051ecd85625518cfd13#types

> A refactor is always about the code itself, and should never change behaviour (assuming good practices). I don't think we should use that as a label for "Changed".

From my perspective, I thought that'd be correct as refactoring code also means you're touching the code (and thus the code changes) but not its behaviour.

I'm okay with adding something like "Miscellaneous". And then only `refactor` label should be included?

2024-03-04 02:37 UTC, adhirajsinghchauhan commented on .github/release.yml
> +        - refactor
`dependencies` and `documentation` too I think.

Also, remind me, why are `package::*` labels excluded in release notes? Sure, the app always fetches the list from the `main` branch (assuming internet connection), but maybe some users still expect to see how much changed between two releases.

Because if there's no internet, on user input, the app can load the list from what's bundled at the time of release.

2024-03-04 10:13 UTC, AnonymousWP commented on .github/release.yml
> +        - refactor
But then the big question is: what label will be part of `Changed`? As `refactor` has been moved to `Miscellaneous`.

> Also, remind me, why are package::* labels excluded in release notes?

From my point of view, this changelog is purely about the application, hence why assets are included. That's one reason. A second reason I'm thinking of is that quite a lot of packages are added (1 line is 1 PR) and thus fills the changelog quite quickly.

I understand your point of view too though. Would a poll here and on the Discord be a good idea? We can't decide for users, so let's see what they expect and want from a changelog when it comes to mentioning packages.

2024-03-04 10:53 UTC, adhirajsinghchauhan commented on .github/release.yml
> +        - refactor
Polling for every little thing is pointless. Either we don't do it, or we do and see how good/bad changelog is.

2024-03-04 11:03 UTC, AnonymousWP commented on .github/release.yml
> +        - refactor
The last poll we had was about the logo. But okay, sure. Let's discuss this internally and then we decide.

And what about my other question?

> But then the big question is: what label will be part of Changed? As refactor has been moved to Miscellaneous.

2024-03-08 05:59 UTC, adhirajsinghchauhan commented on .github/release.yml
> +        - refactor
The Added-Changed-Fixed etc. format is not suited for automatically generated changelogs, because they can't always be paired with the correct label. Often `enhancement`s can be considered as both added _and_ changed, if it happens to introduce a new feature as a side-effect to improving/modifying something else.

I'm assuming we picked up this format from https://keepachangelog.com, but that site came to be at a time where there was no automatic generation anywhere. It recommends using CHANGELOG.md; however, I'd argue that it was designed _only_ for separate files that are checked into repositories (i.e. explicitly requires human review).

**IMO we should move away from this format. We can combine "Added" and "Changed" into simply "Features".**

2024-03-10 12:58 UTC, AnonymousWP commented on .github/release.yml
> +        - refactor
> IMO we should move away from this format. We can combine "Added" and "Changed" into simply "Features".

This basically means renaming `Added` to `Features`, as `Changed` had only one label named `refactor`. But refactor is now part of `Miscellaneous`, so that's no longer relevant. So now it'll be like this:

![image](https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/assets/50231698/c259e483-2980-4715-98c1-e32e69e07692)

2024-03-12 22:29 UTC, AnonymousWP commented
Re-requesting a review from Adhiraj as he previously requested changes, which should now have been solved.

2024-03-13 12:15 UTC, adhirajsinghchauhan approved these changes

2024-03-13 12:15 UTC, merged