pkg: update some samsung packages
Universal-Debloater-Alliance/universal-android-debloater-next-generation pull request #312
Opened 2024-03-03 11:38 UTC by prakharb5

2024-03-03 12:37 UTC, AnonymousWP requested changes

2024-03-03 12:37 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "description": "Samsung Knox allows business and personal content to \"securely\" coexist on the same handset.\nThis package handles proxies alongside KNOX.",
Any reason why the Wikipedia pages have been removed?

2024-03-03 12:37 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "description": "Boot agent\nUCS is a company which has partnered with Samsung to provide licenses for Samsung Knox\nhttps://www.ucssolutions.com/blog/samsung-knox/\nI don't have precise informati
```suggestion
    "description": "Boot agent\nUCS is a company which has partnered with Samsung to provide licenses for Samsung Knox\nhttps://www.ucssolutions.com/blog/samsung-knox/\nI don't have precise information about the package itself but there are chances that it verifies some files on boot. If these files are not verified then it prevents the phone to boot.\n",
```

2024-03-03 12:37 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "description": "Boot agent\nUCS is a company which has partnered with Samsung to provide licenses for Samsung Knox\nhttps://www.ucssolutions.com/blog/samsung-knox/\nI don't have precise informati
Uhm, also, if it is like that, shouldn't it be `Unsafe` then? It's now `Recommended`.

2024-03-03 12:37 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "description": "Bluetooth Test\nHidden feature accessible by entering *#*#232331#*#* in the Samsung dialer.\nIt waas found to be calling home back in 2015 (https://forum.xda-developers.com/galaxy
```suggestion
    "description": "Bluetooth Test\nHidden feature accessible by entering *#*#232331#*#* in the Samsung dialer.\nIt was found to be calling home back in 2015:\nhttps://forum.xda-developers.com/galaxy-s5/help/bluetoothtest-apk-calling-home-t3035182",
```

2024-03-03 12:37 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "description": "Samsung Capture\nSamsung's implementation of screenshot. Show the bottom toolbar after taking a screenshot\n\nLets you group widgets on OneUI 4 (?)",
```suggestion
    "description": "Samsung Capture\nSamsung's implementation of screenshot. Show the bottom toolbar after taking a screenshot\nLets you group widgets on OneUI 4 (?)",
```

2024-03-03 12:37 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "description": "Safe to remove if not using VoWifi.\n#\nHuh... that's hard to explain quickly. Let's try : \nFirst you need to know that there is a standards organization which develops protocols
```suggestion
    "description": "Safe to remove if you're not using VoWifi.\nFirst you need to know that there is a standards organization which develops protocols for mobile telephony called 3GPP (mobile network : 2G/3G/4G/5G).\nRAT (physical connection method to a wireless communication network) non specified by the 3GPP is called non-3GPP. RAT Wifi is non-3GPP.\nePDG means Evolved Packet Data Gateway. The main role of the ePDG is to provide security mechanisms such as IPsec tunnelling of connections with the device over an untrusted non-3GPP access. It is mainly used for VoWifi (Voice over wifi). For more information:\n- https://www.3gpp.org/technologies/keywords-acronyms/100-the-evolved-packet-core\n- https://www.aptilo.com/solutions/mobile-data-offloading/3gpp-wifi-access/\n- https://en.wikipedia.org/wiki/System_Architecture_Evolution#Evolved_Packet_Core_(EPC)",
```

2024-03-04 16:41 UTC, prakharb5 commented on resources/assets/uad_lists.json
> +    "description": "Samsung Knox allows business and personal content to \"securely\" coexist on the same handset.\nThis package handles proxies alongside KNOX.",
That description was related to another app, not this one.

2024-03-04 16:41 UTC, prakharb5 commented on resources/assets/uad_lists.json
> +    "description": "Boot agent\nUCS is a company which has partnered with Samsung to provide licenses for Samsung Knox\nhttps://www.ucssolutions.com/blog/samsung-knox/\nI don't have precise informati
I didn't see that. Will make the change.

2024-03-04 16:44 UTC, prakharb5 commented on resources/assets/uad_lists.json
> +    "description": "Samsung Capture\nSamsung's implementation of screenshot. Show the bottom toolbar after taking a screenshot\n\nLets you group widgets on OneUI 4 (?)",
I added the extra \n since those points are different. I'd say keeping that extra space is better

2024-03-04 17:43 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "description": "Samsung Capture\nSamsung's implementation of screenshot. Show the bottom toolbar after taking a screenshot\n\nLets you group widgets on OneUI 4 (?)",
That's not necessary and we'd like to keep it consistent across packages in the list (meaning it's not the case for other packages as well).

2024-03-05 17:45 UTC, AnonymousWP requested changes
Nitpick, but after this change, this PR can be merged.

2024-03-05 17:45 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "description": "Samsung Nearby device scanning\n#\nNeeds \"com.samsung.android.beaconmanager\" to be useful.\n",
```suggestion
    "description": "Samsung Nearby device scanning\nRequires \"com.samsung.android.beaconmanager\" to be useful.",
```

2024-03-11 23:24 UTC, AnonymousWP commented
@prakharb5 Please follow up on this so we can merge this ASAP. 🙂

2024-03-15 18:03 UTC, AnonymousWP approved these changes

2024-03-15 18:03 UTC, merged