Huawei Packages, Fixes
Universal-Debloater-Alliance/universal-android-debloater-next-generation pull request #322
Opened 2024-03-09 13:29 UTC by Blitz517

Removed some google play links that not exist,
added packages,
changed some descriptions

2024-03-11 20:32 UTC, AnonymousWP requested changes
Didn't go through all typos as that'd require too much work, but some typos were major enough to correct.

2024-03-11 20:32 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "description": "AI Life\nRequire Logging in to your Huawei ID, HMSCore.\nIt's app that lets your control and mamage routers and audio accessories.",
```suggestion
    "description": "AI Life\nRequire Logging in to your Huawei ID, HMSCore.\nIt's an app that lets your control and manage routers and audio accessories.",
```

2024-03-11 20:32 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "description": "SMS Encryption Service, looks maded for China.",
```suggestion
    "description": "SMS Encryption Service, looks made for China.",
```

2024-03-11 20:32 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "removal": "Expert"
```suggestion
    "removal": "Advanced"
```

2024-03-11 20:32 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "description": "Smart headset control\nHas a lot logs and frameworks to mmitest.",
> mmitest

Typo?

2024-03-11 20:32 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "removal": "Advanced"
```suggestion
    "removal": "Recommended"
```
If it's very bloated and doesn't break anything, then shouldn't it be `Recommended`?

2024-03-11 20:32 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "description": "Protect your privacy by preventing apps from accessing sensitive data stored within images,\nsuch as location info and time stamps. This restriction does not apply to system apps
```suggestion
    "description": "Protect your privacy by preventing apps from accessing sensitive data stored within images,\nsuch as location info and time stamps. This restriction does not apply to system apps such as Gallery and Cloud.\nI don't think this app values privacy a lot.",
```

2024-03-11 20:32 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "removal": "Recommended"
```suggestion
    "removal": "Advanced"
```

2024-03-11 20:32 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "removal": "Recommended"
```suggestion
    "removal": "Advanced"
```

2024-03-11 20:40 UTC, Blitz517 commented on resources/assets/uad_lists.json
> +    "description": "Probably safe to remove if you don't play games.\nHas window show, keybind set and more things.",
I can believe its for testing tools.

2024-03-11 20:40 UTC, Blitz517 commented on resources/assets/uad_lists.json
> +    "description": "Huawei stock video application.\nReplace with VLC, which integrates well with the stock gallery.\nHas a lot tracking.",
Has a lot of tracking, better to keep recommended, but remove the recommended alternative.

2024-03-11 20:43 UTC, Blitz517 commented on resources/assets/uad_lists.json
> +    "removal": "Recommended"
I have never seen anyone using this feature (on huawei completely).

2024-03-11 20:44 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "description": "Huawei stock video application.\nReplace with VLC, which integrates well with the stock gallery.\nHas a lot tracking.",
Alright.

2024-03-11 20:45 UTC, Blitz517 commented on resources/assets/uad_lists.json
> +    "description": "foundation\nHas hwid, vehicle things, Aosp In Call Service permissions.\nDisable app instead of uninstalling, because breaks calling.",
breaks calling only if you uninstall, maybe ``advanced``?

2024-03-11 20:46 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "description": "Probably safe to remove if you don't play games.\nHas window show, keybind set and more things.",
If we're not sure, which we probably don't, then `Advanced` is the way to go. I believe it could be something like OnePlus' Gaming Center to use optimal settings of the device for that specific game. Could that be it?

2024-03-11 20:46 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "removal": "Recommended"
How many people do you know using Huawei? 😅

2024-03-11 20:47 UTC, Blitz517 commented on resources/assets/uad_lists.json
> +    "description": "OneHopSvcClient\nTagService, HarmonyTag.",
code of this app is too small

2024-03-11 20:48 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "description": "foundation\nHas hwid, vehicle things, Aosp In Call Service permissions.\nDisable app instead of uninstalling, because breaks calling.",
No, sorry, I really can't agree with that. Calling is a vital function, so there's no reason to make it `Advanced`. Our FAQ is very clear about that.

2024-03-11 20:49 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "description": "OneHopSvcClient\nTagService, HarmonyTag.",
Alright, so there's nothing more to say about it? I also can't find useful information about it. Then leave it as-is indeed.

2024-03-11 20:54 UTC, Blitz517 commented on resources/assets/uad_lists.json
> +    "description": "Smart headset control\nHas a lot logs and frameworks to mmitest.",
no, also found things to com.huawei.vassistant command wakeup if its probably unused?
a lot HwLog, MmiTest running: true
maybe useful in china? looks like a yes

2024-03-11 20:55 UTC, Blitz517 commented on resources/assets/uad_lists.json
> +    "removal": "Advanced"
wait, it has less privacy issues, but may be recommended

2024-03-11 20:59 UTC, Blitz517 commented on resources/assets/uad_lists.json
> +    "description": "Probably safe to remove if you don't play games.\nHas window show, keybind set and more things.",
then advanced, but the old huawei doesn't look like it has much gaming stuff (or just completely lacking)

2024-03-11 21:00 UTC, Blitz517 commented on resources/assets/uad_lists.json
> +    "removal": "Recommended"
new huawei: 1% peoples, old huawei: 10-15% in the world

2024-03-11 23:01 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "description": "Probably safe to remove if you don't play games.\nHas window show, keybind set and more things.",
Okay, I'll look forward to your commit.

2024-03-11 23:02 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "removal": "Recommended"
You know, it doesn't matter how many people use it. It's not pointless nor outright negative. Please stick to the FAQ: https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/wiki/FAQ

2024-03-12 16:42 UTC, Blitz517 commented on resources/assets/uad_lists.json
> +    "removal": "Recommended"
😅

2024-03-12 22:17 UTC, AnonymousWP approved these changes

2024-03-12 22:17 UTC, merged