deps(iced): upgrade iced to 0.12
Universal-Debloater-Alliance/universal-android-debloater-next-generation pull request #331
Opened 2024-03-12 18:48 UTC by edgy-b

- upgraded to iced 12

 - fixed white theme dropdown selector color

2024-03-12 21:07 UTC, Frigyes06 requested changes

2024-03-12 21:07 UTC, Frigyes06 commented on Cargo.toml
> +version = "1.1.0"
Please don't bump the UAD version.

2024-03-12 21:07 UTC, Frigyes06 commented on src/core/theme.rs
> +                    primary: color!(0x818181),
Why are you changing the color here?

2024-03-12 21:07 UTC, Frigyes06 commented on src/gui/mod.rs
> +                    width: 1000.0,
Why are you changing the startup size?

2024-03-12 21:11 UTC, Frigyes06 commented
Fixes #326

2024-03-12 22:00 UTC, edgy-b commented on src/gui/mod.rs
> +                    width: 1000.0,
Let's say there is update: buttons get pushed and some are not visible
![old-res](https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/assets/58686023/a1e5da42-467e-41a3-acc3-c14aa0f614c8)
VS new:
![new-res](https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/assets/58686023/eb8d08db-f65d-41e5-bc42-30f4528e60d8)

2024-03-12 22:04 UTC, edgy-b commented on src/core/theme.rs
> +                    primary: color!(0x818181),
To fix dropdown on Light theme.
Old:
![old-drop](https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/assets/58686023/7230ff9a-7892-4eec-962a-126417a2e262)
New:
![new-drop](https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/assets/58686023/5bf83312-6aef-484c-86ce-e2b8a71692a4)

2024-03-12 22:04 UTC, edgy-b commented on Cargo.toml
> +version = "1.1.0"
Ok, will revert back.

2024-03-12 22:14 UTC, AnonymousWP commented
> Fixes #326

This is not how it works. You either need to put it in the description of the author that opened the PR, or link it here:

![image](https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/assets/50231698/b0beb243-fa09-4889-91ec-d03271b1d021)

I've done it now.

2024-03-12 22:16 UTC, AnonymousWP commented
> * upgraded to iced 0.12
> * fixed white theme dropdown selector color

In my opinion the second thing should have been done in a separate PR.

2024-03-14 19:05 UTC, AnonymousWP commented
What are you trying to do exactly? You keep updating this branch without retaining a clean commit history.

2024-03-14 20:28 UTC, edgy-b commented
> What are you trying to do exactly? You keep updating this branch without retaining a clean commit history.

Right👍 I was playing with some bash scripts, crons etc. automation locally, not a good idea on PR branches

2024-03-15 09:48 UTC, AnonymousWP commented
Might as well update to iced 0.12.1 as it comes with important fixes: https://github.com/iced-rs/iced/releases/tag/0.12.1

2024-03-15 10:05 UTC, edgy-b commented
> Might as well update to iced 0.12.1 as it comes with important fixes: https://github.com/iced-rs/iced/releases/tag/0.12.1

It is indeed coming with 0.12.1 in Cargo.lock

2024-03-16 14:23 UTC, AnonymousWP commented
> > Might as well update to iced 0.12.1 as it comes with important fixes: https://github.com/iced-rs/iced/releases/tag/0.12.1
> 
> It is indeed coming with 0.12.1 in Cargo.lock

What do you mean? In your changes I see 0.12.0, not 0.12.1.

2024-03-16 16:17 UTC, edgy-b commented
> > > Might as well update to iced 0.12.1 as it comes with important fixes: https://github.com/iced-rs/iced/releases/tag/0.12.1
> > 
> > 
> > It is indeed coming with 0.12.1 in Cargo.lock
> 
> What do you mean? In your changes I see 0.12.0, not 0.12.1.
https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/pull/331/files#diff-13ee4b2252c9e516a0547f2891aa2105c3ca71c6d7a1e682c69be97998dfc87eR1168

2024-03-17 01:29 UTC, adhirajsinghchauhan commented on src/gui/mod.rs
> +                    width: 1000.0,
Once #340 is merged, you'd need to revisit this to adjust width accordingly.

2024-03-18 00:08 UTC, Frigyes06 approved these changes

2024-03-18 08:50 UTC, merged