Update README.md
Universal-Debloater-Alliance/universal-android-debloater-next-generation pull request #337
Opened 2024-03-14 12:14 UTC by qumuq-til

Added important information to adjust users's expectations regarding what UAD-NG can and cannot do.

2024-03-14 12:46 UTC, AnonymousWP requested changes

2024-03-18 11:46 UTC, AnonymousWP commented
@qumuq-til Please follow-up on this so this can be merged ASAP.

2024-03-18 14:25 UTC, AnonymousWP commented on README.md
> +This can also contribute to improving security by reducing (but not eliminating) [the attack surface](https://en.wikipedia.org/wiki/Attack_surface). Read the [wiki](https://github.com/Universal-Deblo
@qumuq-til Not sure why you marked it as resolved because the suggested changes have not been committed. 😅

2024-03-18 14:29 UTC, qumuq-til commented on README.md
> +This can also contribute to improving security by reducing (but not eliminating) [the attack surface](https://en.wikipedia.org/wiki/Attack_surface). Read the [wiki](https://github.com/Universal-Deblo
Ahhh I'm really unfamiliar with how Github works, unfortunately. So I just pressed every button!

2024-03-18 14:30 UTC, AnonymousWP commented on README.md
> +This can also contribute to improving security by reducing (but not eliminating) [the attack surface](https://en.wikipedia.org/wiki/Attack_surface). Read the [wiki](https://github.com/Universal-Deblo
You can click this button:

![image](https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/assets/50231698/2017ab89-0ea6-455e-bc24-47c7718463a3)

2024-03-18 14:32 UTC, qumuq-til reviewed
Done!

2024-03-18 14:32 UTC, qumuq-til commented on README.md
> +This can also contribute to improving security by reducing (but not eliminating) [the attack surface](https://en.wikipedia.org/wiki/Attack_surface). Read the [wiki](https://github.com/Universal-Deblo
I agree with the proposed changes, if that's what's blocking the request here. Specifically about reducing but not eliminating I see no confusion, because it brings attention to the not eliminating part which could otherwise slip by.

2024-03-18 14:34 UTC, qumuq-til commented on README.md
> +This can also contribute to improving security by reducing (but not eliminating) [the attack surface](https://en.wikipedia.org/wiki/Attack_surface). Read the [wiki](https://github.com/Universal-Deblo
Didn't see that one. Should be good now?

2024-03-18 14:39 UTC, AnonymousWP approved these changes

2024-03-18 14:39 UTC, merged