bug(app): inform user of ADB if not insatlled
Universal-Debloater-Alliance/universal-android-debloater-next-generation pull request #343
Opened 2024-03-16 16:56 UTC by edgy-b

![adb](https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/assets/58686023/5201433a-95ed-4cc9-bed3-4066eeaf8b65)

2024-03-16 18:18 UTC, AnonymousWP requested changes

2024-03-16 18:18 UTC, AnonymousWP commented on src/gui/views/list.rs
> +                    "ADB is not installed in your system, install adb and relaunch application.",
```suggestion
                    "ADB is not installed on your system, install ADB and relaunch application.",
```

2024-03-16 18:46 UTC, AnonymousWP approved these changes

2024-03-16 18:50 UTC, AnonymousWP commented
I'm waiting with merging because I'm requesting a review from our developers.

2024-03-17 01:19 UTC, adhirajsinghchauhan approved these changes

2024-03-17 01:19 UTC, merged