bug(uad-ng): logo not visible on Windows 11 light mode
Universal-Debloater-Alliance/universal-android-debloater-next-generation pull request #364
Opened 2024-03-18 19:36 UTC by edgy-b

- added logo dark logo

2024-03-18 20:32 UTC, AnonymousWP commented
Converted this one to a draft because we're still testing.

2024-03-19 11:02 UTC, AnonymousWP commented
It's now confirmed to work on Windows 10, but not 11 yet for me.

2024-03-20 19:18 UTC, AnonymousWP commented
It's an issue on my end, works elsewhere. Marking this PR as ready. @Universal-Debloater-Alliance/developers can review this now.

2024-03-22 16:24 UTC, Frigyes06 commented
Changing the logo based on system theme and not application setting feels odd to me. We should synchronize the whole app theme with system theme at first startup, then let the user overwrite it in the settings. Or have a setting to synchronize only the logo. We need to allow for more control over this setting.

2024-03-22 16:34 UTC, Frigyes06 requested changes

2024-03-22 16:34 UTC, Frigyes06 commented on resources/assets/logo-dark.png
naming convention, rename this to logo-light, the other one to logo-dark

2024-03-23 03:29 UTC, Frigyes06 approved these changes

2024-03-23 03:30 UTC, merged