Xiaomi more packages / changes
Universal-Debloater-Alliance/universal-android-debloater-next-generation pull request #367
Opened 2024-03-21 13:08 UTC by Blitz517

more information, less disinformation

2024-03-21 20:29 UTC, AnonymousWP requested changes

2024-03-21 20:29 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "description": "Heart Rate\nHidden app, not available for users.\nhttps://www.reddit.com/r/Xiaomi/comments/v0uhhx/found_hidden_heart_rate_app_in_miui_1304_i_opened/\nIn HyperOS, this app looks li
```suggestion
    "description": "Heart Rate\nHidden app, not available for users.\nhttps://www.reddit.com/r/Xiaomi/comments/v0uhhx/found_hidden_heart_rate_app_in_miui_1304_i_opened/\nIn HyperOS, this app looks like it's done.",
```
What do you mean with "it's done"? Deprecated? End-of-life perhaps?

2024-03-21 20:29 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "removal": "Recommended"
```suggestion
    "removal": "Advanced"
```
If the earbud's image doesn't show up anymore for users, it may confuse them and it's hard to get back as users usually uninstall the packages.

2024-03-21 20:29 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "list": "Oem",
Is this present on all phones or only selected OEMs?

2024-03-21 20:29 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "list": "Oem",
Same as above.

2024-03-21 20:29 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "description": "Contain the overlay files and resources specific to the System UI customization.\nThese overlay files can be used to modify various aspects of the System UI, including the navigat
```suggestion
    "description": "Contain the overlay files and resources specific to the System UI customization.\nThese overlay files can be used to modify various aspects of the System UI, including the navigation bar, status bar, lockscreen, and volume dialog.\nhttps://source.android.com/docs/automotive/hmi/system_ui\nhttps://source.android.com/docs/automotive/hmi/system_ui/management_system\nOn some phones, it is an overlay to app \"com.google.android.apps.safetyhub\".\nCheck out this app code and think about it.",
```
You need to escape it like this.

2024-03-21 20:29 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "removal": "Advanced"
```suggestion
    "removal": "Expert"
```
Concerns core system.

2024-03-21 20:29 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "description": "Eid-Service\nIt's something about card chips or online identity? Useful only in China.\nHas a lot logs in code.",
```suggestion
    "description": "Eid-Service\nIt's something about card chips or online identity? Useful only in China.\nHas a lot of logs in code.",
```

2024-03-21 20:29 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "removal": "Advanced"
```suggestion
    "removal": "Recommended"
```
Mi Video is recommended right? Then why this is not?

2024-03-21 20:29 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "description": "'I always on' found in code and a lot statistics. Also Miui analytics permissions.",
What is "I always on" for?

2024-03-21 20:29 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "description": "Needed to WiFi.",
```suggestion
    "description": "Needed for WiFi.",
```

2024-03-21 20:29 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "description": "XiaoaiRecommendation\nThis app does nothing, totally random frameworks unused.",
```suggestion
    "description": "XiaomiRecommendation\nThis app does nothing, totally random frameworks unused.",
```

2024-03-21 23:34 UTC, Blitz517 commented on resources/assets/uad_lists.json
> +    "description": "A improve touch things was found in the code, but it is not available to users, only to developers.\nThe size of the app is 36.40 KB, so why would this improve touch?\nThis app do
so thats it, advanced

2024-03-21 23:36 UTC, Blitz517 commented on resources/assets/uad_lists.json
> +    "removal": "Advanced"
but some apps for vowifi or volte was already set advanced

2024-03-21 23:37 UTC, Blitz517 commented on resources/assets/uad_lists.json
> +    "removal": "Advanced"
stay on advanced, this app not cause bootloop, just lose some a little functionality, guess its not for cast screen

2024-03-21 23:39 UTC, Blitz517 commented on resources/assets/uad_lists.json
> +    "description": "Heart Rate\nHidden app, not available for users.\nhttps://www.reddit.com/r/Xiaomi/comments/v0uhhx/found_hidden_heart_rate_app_in_miui_1304_i_opened/\nIn HyperOS, this app looks li
this app is done and there are no hidden activities like on miui 14: https://www.apkmirror.com/apk/xiaomi-inc/mi-health/mi-health-1-0-6-release/mi-health-1-0-6-android-apk-download/

2024-03-21 23:41 UTC, Blitz517 commented on resources/assets/uad_lists.json
> +    "removal": "Recommended"
i never seen these images maybe unused or for specific xiaomi earbuds, but its only app with png, webp files

2024-03-21 23:42 UTC, Blitz517 commented on resources/assets/uad_lists.json
> +    "removal": "Recommended"
so advanced i guess, no trackers, no activities

2024-03-21 23:42 UTC, Blitz517 commented on resources/assets/uad_lists.json
> +    "list": "Oem",
only for xiaomi i have seen

2024-03-21 23:44 UTC, Blitz517 commented on resources/assets/uad_lists.json
> +    "removal": "Advanced"
it might be not true...

2024-03-21 23:46 UTC, Blitz517 commented on resources/assets/uad_lists.json
> +    "removal": "Advanced"
its because of its completly different version, no trackers app

2024-03-21 23:50 UTC, Blitz517 commented on resources/assets/uad_lists.json
> +    "description": "'I always on' found in code and a lot statistics. Also Miui analytics permissions.",
looks like a screen on/off, this app is for tracking

2024-03-21 23:51 UTC, Blitz517 commented on resources/assets/uad_lists.json
> +    "description": "XiaoaiRecommendation\nThis app does nothing, totally random frameworks unused.",
real name of this app is XiaoaiRecommendation, its not a joke!

2024-03-21 23:59 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "removal": "Advanced"
Then that should be corrected too in my opinion.

2024-03-22 11:46 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "removal": "Advanced"
Then you've not read the FAQ correctly. `Expert` isn't about bootlooping; `Unsafe` is.

2024-03-22 11:46 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "description": "Heart Rate\nHidden app, not available for users.\nhttps://www.reddit.com/r/Xiaomi/comments/v0uhhx/found_hidden_heart_rate_app_in_miui_1304_i_opened/\nIn HyperOS, this app looks li
Yeah okay, so you mean it's deprecated. Please mention that in the description. Not many people would understand what you mean with "It's done".

2024-03-22 12:28 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "removal": "Advanced"
What do you mean?

> System UI, including the navigation bar, status bar, lockscreen, and volume

This is an essential part of Android.

2024-03-22 12:29 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "description": "'I always on' found in code and a lot statistics. Also Miui analytics permissions.",
So something like AOD?

2024-03-22 14:26 UTC, Blitz517 commented on resources/assets/uad_lists.json
> +    "removal": "Advanced"
now i get it "com.android.overlay.systemui" is for xiaomi oem overlay (weird is theres things to safetyhub and chromecast app that nothing does) and: "com.android.systemui.overlay" is a probably this one app that is aosp and unsafe to remove

give it to expert and keep only this? :On some phones, it is an overlay to app \"com.google.android.apps.safetyhub\".\nCheck out this app code and think about it.

2024-03-22 14:37 UTC, Blitz517 commented on resources/assets/uad_lists.json
> +    "description": "'I always on' found in code and a lot statistics. Also Miui analytics permissions.",
its AON, IAlwaysOn
more things founded to FaceEventRegister(still tracker) FlareEventRegister
totally random things with debugging
has AONEventTracking (miui china, sends to com.miui.analytics (tracks device region, non anonymous, actually not too much, weird app with tracking no one knows what.)) miface things founded in vendor like a they spying face and everything you do on phone? who knows

2024-03-22 14:37 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "removal": "Advanced"
Uhh, keep this one expert and leave the other one unsafe I guess?

2024-03-22 14:39 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "description": "'I always on' found in code and a lot statistics. Also Miui analytics permissions.",
Perhaps face unlock?

2024-03-22 15:05 UTC, Blitz517 commented on resources/assets/uad_lists.json
> +    "removal": "Advanced"
keep expert and remove old description

2024-03-22 15:05 UTC, Blitz517 commented on resources/assets/uad_lists.json
> +    "description": "'I always on' found in code and a lot statistics. Also Miui analytics permissions.",
theres nothing about face unlock

2024-03-22 15:17 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "removal": "Advanced"
Yeah sure.

2024-03-22 15:18 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "description": "'I always on' found in code and a lot statistics. Also Miui analytics permissions.",
Hmm okay, no idea then.

2024-03-22 18:19 UTC, AnonymousWP approved these changes

2024-03-22 18:20 UTC, merged

2024-03-23 10:55 UTC, Hamza417 commented
The JSON structure is broken in this pull request, why was this approved without checking for that? The file structure goes in [this format](https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/blob/c757f1a5067833a485d5de0dc5111dd60c5df5b4/resources/assets/uad_lists.json#L35736-L35743), but the [changes added here](https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/blob/c757f1a5067833a485d5de0dc5111dd60c5df5b4/resources/assets/uad_lists.json#L35752-L36327) do not adhere to that.