Add Archive Link for Twitter (uad_lists.json)
Universal-Debloater-Alliance/universal-android-debloater-next-generation pull request #396
Opened 2024-03-30 03:21 UTC by TechFanTheo

2024-03-30 12:55 UTC, AnonymousWP requested changes

2024-03-30 12:55 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "description": "Named 'MTBF Tools'\nDialer Code: 68238665. Uses SQLite Database. Reads/writes to External Storage. All sorts of permissions (camera, mic, battery, radio, led, sim, gps, nfc).\nFou
```suggestion
    "description": "Named 'MTBF Tools'\nDialer Code: 68238665. Uses SQLite Database. Reads/writes to External Storage. All sorts of permissions (camera, mic, battery, radio, led, sim, gps, nfc).\nFound more details at https://twitter.com/dbauduin/status/940126704261099520 (archive: https://web.archive.org/web/20240330025312/https://twitter.com/dbauduin/status/940126704261099520)\nHardcoded URLs (an api and a book): http://www.andykhan.com/jexcelapi\nhttp://www.amazon.co.uk/exec/obidos/ASIN/0571058086/qid=1099836249/sr=1-3/ref=sr_1_11_3/202-6017285-1620664\nhttps://www.amazon.co.uk/exec/obidos/ASIN/0571058086qid=1099836249/sr=1-3/ref=sr_1_11_3/202-6017285-1620664",
```

2024-04-16 05:34 UTC, TechFanTheo commented
Sorry I didn't now I had to approve the suggestion. Look like it is outdated and cannot be aplied.

2024-04-16 07:43 UTC, AnonymousWP commented
> Sorry I didn't now I had to approve the suggestion. Look like it is outdated and cannot be aplied.

In that case you need to push a new commit from your local system to this PR. Just change it on your computer and then push.

2024-05-04 16:41 UTC, AnonymousWP commented
@TechFanTheo See above.

2024-05-20 12:28 UTC, closed without merging