Samsung More Packages + Pending Packages
Universal-Debloater-Alliance/universal-android-debloater-next-generation pull request #402
Opened 2024-04-02 17:57 UTC by Blitz517

Some Pending Packages Explained, Added more unlisted apps.

2024-04-05 12:45 UTC, AnonymousWP requested changes
This review is WIP. I'll finish the others later.

2024-04-09 10:05 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "description": "Hidden network stats in code found.",
Not sure how reliable this is, but it doesn't look like it should be `Recommended`: https://www.reddit.com/r/GalaxyS23/comments/18cv53y/do_you_guys_know_what_that_is_and_if_youve_got/

2024-04-10 15:47 UTC, Blitz517 commented on resources/assets/uad_lists.json
> +    "description": "Generic Bootstrapping Architecture. A ‘common ground’ of code used for many MediaTek apps.\nCan be removed if all other MediaTek apps are removed.",
idk, this app is from https://www.olorin.me/2020/02/11/debloating-the-umidigi-f2/
also com.mediatek.gbaservice has the same description.
I can tell whats in the app because truth is other now i see:
Generic Bootstrapping Architecture
has ims, X-TMUS-IMEI, bsf.msg.lab.t-mobile.com things
its to encrypted calls ims probably (thinking by looking classes.dex code)
connects to site bsf.ims.mncXXX.pub.3gppnetwork.org

2024-04-10 15:49 UTC, Blitz517 commented on resources/assets/uad_lists.json
> +    "removal": "Advanced"
looks like a its features for main camera app only

2024-04-10 15:51 UTC, Blitz517 commented on resources/assets/uad_lists.json
>      "description": "",
some apps by name not looks like expert, no descriptions because of i dont know how to get these packages
TCL phone roms sometimes cant be extracted

2024-04-10 15:53 UTC, Blitz517 commented on resources/assets/uad_lists.json
> +    "removal": "Unsafe"
its not bootloop phone but its highly not recommended when transfer files to pc/phone will not work,
i can add to description its not cause bootloop but its highly not recommended removing that

2024-04-10 16:09 UTC, Blitz517 commented on resources/assets/uad_lists.json
> +    "removal": "Recommended"
um this knox app is weird, its unused, many knox app has the same things like this, checking classes.dex theres a lot useless stuff like analytics, enterprise, license, integrity so i only say about mpos, theres pay info things with too small code and certificate here. Its another app to activate knox license when i have seen this app on google play:
https://play.google.com/store/apps/details?id=com.samsung.android.knox.mpos

2024-04-10 16:11 UTC, Blitz517 commented on resources/assets/uad_lists.json
> +    "removal": "Unsafe"
probably not, needed for Gesture navigation

2024-04-10 16:12 UTC, Blitz517 commented on resources/assets/uad_lists.json
> +    "removal": "Unsafe"
i will change them 3 to expert

2024-04-10 16:15 UTC, Blitz517 commented on resources/assets/uad_lists.json
> +    "description": "TNCPageCN\nIt's app for enhance lock screen.",
its like a also samsung notifications app but in china, this app still looks china only

2024-04-10 16:28 UTC, Blitz517 commented on resources/assets/uad_lists.json
> +    "description": "Hidden network stats in code found.",
I tried to find more so this app is from qualcomm, in androidmanifest.xml I found things like com.qualcomm.qti.qmsdataservices, qms is spyware, permissions uses: access wifi state, quary all packages, package usage stats. So hidden network stats, more about it is this code is just logs, takes apm, wifi, bt status. I gave too small a description first time, my mistake.
On this site what you send, AI only by name tried to say whats that app is, but he failed.

2024-04-10 16:31 UTC, Blitz517 commented on resources/assets/uad_lists.json
> +    "removal": "Recommended"
switch camera local, virtual camera things. So Advanced

2024-04-11 17:48 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "description": "Generic Bootstrapping Architecture. A ‘common ground’ of code used for many MediaTek apps.\nCan be removed if all other MediaTek apps are removed.",
In that case it should definitely not be `Recommended`, but at least `Advanced`.

2024-04-11 17:49 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "removal": "Advanced"
How certain are you about this?

2024-04-11 17:52 UTC, AnonymousWP commented on resources/assets/uad_lists.json
>      "description": "",
We can't just assume that based on the name, so please keep it `Expert`.

2024-04-11 17:52 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "removal": "Unsafe"
Yes please, that's more clear.

2024-04-11 17:54 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "removal": "Recommended"
I doubt it's unused, check the Play Store description, so maybe make it `Advanced`:

> Knox mPOS Enabler offers a range of security/usability features, enabling secure and contactless payments on Samsung devices.

2024-04-11 17:54 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "removal": "Unsafe"
`Expert` fits better then.

2024-04-11 17:55 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "description": "Hidden network stats in code found.",
For the little we know about this package, I think it's quite risky to keep it `Recommended`.

2024-04-11 17:56 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "removal": "Recommended"
Yeah.

2024-04-11 18:21 UTC, Blitz517 commented on resources/assets/uad_lists.json
> +    "removal": "Advanced"
Wait, it is not confirmed that this application is for calibration, it has many permissions from the lib ...
There are a lot of features that I do not know if it is not only available to developers. Many arcsoft, smartcamerascan, supernight, too many to write here. A strange application with many things sometimes mentioned in the code that it is used for calibration ... so ``Expert``

2024-04-11 18:24 UTC, Blitz517 commented on resources/assets/uad_lists.json
>      "description": "",
Unfortunately, even if the 90% chance that this app is just a normal app and is still put in advanced

2024-04-11 18:26 UTC, Blitz517 commented on resources/assets/uad_lists.json
> +    "removal": "Recommended"
i will take your desc.

2024-04-11 18:27 UTC, Blitz517 commented on resources/assets/uad_lists.json
> +    "removal": "Recommended"
its optional app but yep

2024-04-11 18:53 UTC, AnonymousWP commented on resources/assets/uad_lists.json
>      "description": "",
We can't know though, so that's assuming.

2024-04-12 10:49 UTC, AnonymousWP approved these changes

2024-04-12 10:52 UTC, AnonymousWP requested changes
I've overseen that not all conversations have been solved, so there's one more request from my side: see pending conversation about leaving it `Expert`.

2024-04-12 11:07 UTC, AnonymousWP approved these changes

2024-04-12 11:07 UTC, merged