feat(app): exclude windows terminal attach
Universal-Debloater-Alliance/universal-android-debloater-next-generation pull request #414
Opened 2024-04-08 20:24 UTC by Frigyes06

2024-04-08 21:08 UTC, Frigyes06 commented
I will eat my hat

2024-04-09 11:50 UTC, edgy-b commented on src/main.rs
> +/// Also attaches the terminalon windows machines
Small typo mistake `terminal on`

2024-04-09 16:06 UTC, edgy-b approved these changes

2024-04-09 16:13 UTC, AnonymousWP requested changes

2024-04-09 16:13 UTC, AnonymousWP commented on src/main.rs
> +    /// Attach Windows terminal, only on windows
```suggestion
    /// Attach Windows terminal, only on Windows
```

2024-04-09 16:13 UTC, AnonymousWP commented on src/main.rs
> +/// This is excluded on non-windows targets.
```suggestion
/// This is excluded on non-Windows targets.
```

2024-04-09 17:55 UTC, AnonymousWP approved these changes

2024-04-09 17:55 UTC, merged

2024-04-09 17:56 UTC, AnonymousWP commented
Approved & merged, but if you could add some small explanation in the description, then that'd be great.