Warning about potential breakage on infinix phones
Universal-Debloater-Alliance/universal-android-debloater-next-generation pull request #426
Opened 2024-04-17 00:20 UTC by l-theanine

Removing this package breaks entering password on lockscreen (after initial boot)

I had to connect a physical keyboard, unlock my phone, and then restore the app again.

2024-04-17 11:58 UTC, AnonymousWP requested changes

2024-04-17 11:58 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "description": "Emoji Keyboard\nHave ads and it's not good for privacy.\nWARNING: Oh infinix phones, this package is a hard dependency to show keyboard after initial reboot/startup. Without it, e
```suggestion
    "description": "Emoji Keyboard\nHave ads and it's not good for privacy.\nWARNING: On Infinix phones, this package is a hard dependency to show keyboard after initial reboot/startup. Without it, even if you have another keyboards installed, no keyboard will show.\nDon't remove if you're using an Infinix and need to enter password after boot.",
```

2024-04-19 07:42 UTC, l-theanine commented on resources/assets/uad_lists.json
> +    "description": "Emoji Keyboard\nHave ads and it's not good for privacy.\nWARNING: Oh infinix phones, this package is a hard dependency to show keyboard after initial reboot/startup. Without it, e
Hey, I am unable to commit suggestion as this error keeps showing up. 

"This diff has recently been updated. Refresh and try again.". Refreshing however, does not work.

![screenshot](https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/assets/161464716/a78770eb-1afe-4637-a634-b19eb416730c)

2024-04-19 08:18 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "description": "Emoji Keyboard\nHave ads and it's not good for privacy.\nWARNING: Oh infinix phones, this package is a hard dependency to show keyboard after initial reboot/startup. Without it, e
Hi, yeah that's correct. It's a GitHub bug, so in that case you should commit it to your branch directly and change it manually.

2024-04-19 10:40 UTC, AnonymousWP approved these changes

2024-04-19 10:42 UTC, merged