feat(backup): add ability to export uninstalled packages with their description
Universal-Debloater-Alliance/universal-android-debloater-next-generation pull request #527
Opened 2024-06-30 17:33 UTC by edgy-b

- fixed some deepsource issues

Resolves #173

2024-07-01 01:34 UTC, adhirajsinghchauhan requested changes
Code passes the eye test, but are we sure we want to stick with txt? This looks weird to me:
```
Name: <app 1>
Description: <multiline
text>
-------------------------------------------------------------------
Name: <app 2>
Description: <text>
```
I'd rather have it exported in other formats such as CSV. Can still be opened in a text editor, but at least users could potentially use other programs to view/filter through everything.

2024-07-01 01:36 UTC, adhirajsinghchauhan requested changes

2024-07-01 01:36 UTC, adhirajsinghchauhan commented on src/core/utils.rs
> +                "-------------------------------------------------------------------\n",
If we end up sticking with txt, consider making this separator string a `const` somewhere up above, so that we can reuse it elsewhere.

2024-07-03 04:57 UTC, adhirajsinghchauhan approved these changes

2024-07-03 04:58 UTC, merged

2024-07-03 23:12 UTC, Rudxain commented on src/core/save.rs
>  // Backup all `Uninstalled` and `Disabled` packages
Why is this a regular comment rather than a doc?