DOOGEE OEM Packages
Universal-Debloater-Alliance/universal-android-debloater-next-generation pull request #542
Opened 2024-07-08 18:29 UTC by Blitz517

2024-07-08 20:19 UTC, AnonymousWP requested changes

2024-07-08 20:19 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "removal": "Advanced"
If this is a Doogee app, then it should be `Recommended`. There are much better alternatives than stock app of Doogee.

2024-07-08 20:19 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "removal": "Recommended"
Why is this `Recommended`?

2024-07-08 20:19 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "removal": "Advanced"
```suggestion
    "removal": "Recommended"
```

2024-07-08 20:19 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "removal": "Expert"
```suggestion
    "removal": "Advanced"
```

2024-07-08 20:19 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "removal": "Recommended"
```suggestion
    "removal": "Expert"
```
Gestures are important.

2024-07-08 20:19 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "description": "S-capture\nFounded in the app: Screen record, screenshot, Test Launcher.",
```suggestion
    "description": "S-capture\nFound in the app: Screen record, screenshot, Test Launcher.",
```

2024-07-09 13:21 UTC, Blitz517 commented on resources/assets/uad_lists.json
> +    "removal": "Advanced"
no trackers/ads so theres no difference probably

2024-07-09 13:21 UTC, Blitz517 commented on resources/assets/uad_lists.json
> +    "removal": "Recommended"
because its recommended on other OEM's

2024-07-09 13:22 UTC, Blitz517 commented on resources/assets/uad_lists.json
> +    "removal": "Expert"
normal game mode like in aosp ADVANCED

2024-07-10 17:06 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "removal": "Advanced"
Does it work via camera or is it a separate app?

2024-07-10 17:08 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "removal": "Recommended"
Hmm, I don't think that's supposed to be `Recommended` either on other apps. It should probably be `Advanced`.

2024-07-11 20:31 UTC, Blitz517 commented on resources/assets/uad_lists.json
> +    "removal": "Advanced"
Looks like a its feature to camera, cannot normally run it like a icon in launcher android.

2024-07-11 20:32 UTC, Blitz517 commented on resources/assets/uad_lists.json
> +    "removal": "Expert"
set in advanced

2024-07-11 20:33 UTC, Blitz517 commented on resources/assets/uad_lists.json
> +    "removal": "Recommended"
but every like this type of app is recommended

2024-07-12 08:32 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "removal": "Advanced"
Ooh okay, then `Advanced` is good indeed.

2024-07-12 16:09 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "removal": "Recommended"
Can you tell me where? Because it shouldn't. These apps can be useful and third-party apps from Play Store probably don't have as many permissions as these built-in OEM apps.

2024-07-12 17:47 UTC, Blitz517 commented on resources/assets/uad_lists.json
> +    "removal": "Recommended"
I mean if you search on uad lists for example samsung, its not app from play store, don't have too much permissions.

2024-07-14 11:29 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "removal": "Expert"
You didn't set it to `Advanced` yet.

2024-07-14 11:29 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "removal": "Advanced"
Why marking it as resolved if you didn't change it yet?

2024-07-14 11:30 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "removal": "Recommended"
Same as above.

2024-08-10 13:02 UTC, AnonymousWP commented
Closing this due to inactivity. I'll re-open them myself.

2024-08-10 13:02 UTC, closed without merging

2025-02-03 02:58 UTC, Rudxain commented
@Universal-Debloater-Alliance/package-contributors what do we do with this?