chore(fix-lints): fix warnings from #537
Universal-Debloater-Alliance/universal-android-debloater-next-generation pull request #578
Opened 2024-08-06 20:46 UTC by Rudxain

Follow-up of #537. Fixing warns/errs triggered by enabled lints, potentially `allow`ing sensible cases

2024-08-07 15:58 UTC, Rudxain commented
@AnonymousWP I'm also confused about the PR type, lol.

As of now, it might seem like these changes are `style` only, and applying/fixing lints usually is `refactor`, but there will be some slight **behavior changes** which implies `feat` or `fix`. However, the changes don't seem significant enough to justify any of those types, so I defaulted to `chore`

2024-08-07 18:21 UTC, AnonymousWP commented
Yeah it's okay, it doesn't really matter much. Use what's logical for you. 😄

2024-09-06 17:34 UTC, AnonymousWP commented
> [1.81 has been stabilized!](https://github.com/rust-lang/rust/releases/tag/1.81.0) 🎉. We can finally [`expect`](https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/pull/537#issuecomment-2274014453)

Are you planning to implement that in this PR or in a new PR eventually?

2024-09-07 05:10 UTC, Rudxain commented
> this PR or in a new PR eventually?

Good question. `expect` is (in some cases) identical to `allow`, so this is still scope-relevant. There shouldn't be a need for another PR

2024-09-13 09:49 UTC, Rudxain commented
I believe this should be merged as-is, despite some `warn`ings remaining. For these reasons:
- I can't fix all `warn`s alone, such as `too_many_lines`.
- Some `warn`s are unclear how to handle. Not all `unwrap`s should use implicit/explicit defaults, but sometimes it's appropriate. Some `unwrap()`s should simply be converted to `expect()` (not the `#[expect]` attribute) where appropriate. I don't have enough knowledge of the app to decide this on my  own.
- I'm becoming busy IRL and digitally, so this PR will be blocked because of external factors.
- `main` has a bunch of unresolved `warn`s that are distracting. It'd be better if we merge this now, then fix the remaining warns opportunistically.

I think I've made enough progress, as there were ~93 `warn`s, that I reduced to 20!

2024-09-14 03:09 UTC, lavafroth requested changes
Just that one nit, looks fine otherwise.

2024-09-14 03:09 UTC, lavafroth commented on src/core/theme.rs
> +                background: color!(0x11_11_11),
I know this was probably automated but the whole point of using the hex values was so that you could chuck in the hex color values into some tool to see the color or quicky paste hex values from a predefined colorscheme.

2024-09-14 11:17 UTC, adhirajsinghchauhan commented on src/core/theme.rs
> +                background: color!(0x11_11_11),
Agreed, let's revert this. Some editor extensions can also display colors inline, but only if they're continuous hex (i.e. not separated by underscores etc.)

2024-09-14 12:39 UTC, Rudxain commented on src/core/theme.rs
> +                background: color!(0x11_11_11),
_Partially_ automated. It was **much** worse: `0x0011_1111`. I'll remove the underscores in a moment...

2024-09-14 13:27 UTC, lavafroth approved these changes

2024-09-14 14:13 UTC, merged