pkg(com.lge.sui.widget): change description and removal
Universal-Debloater-Alliance/universal-android-debloater-next-generation pull request #588
Opened 2024-08-20 18:01 UTC by alvinkim101

Removing this package causes the clock app to crash when setting an alarm to a specific date. Tested on my LG G6.

2024-08-20 19:12 UTC, AnonymousWP requested changes

2024-08-20 19:12 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "description": "Used by the alarm clock to select a specific date from the calendar instead of a day of the week.",
```suggestion
    "description": "Used by the alarm clock to select a specific date from the calendar instead of a day of the week. Removing this package causes the clock app to crash when trying to set a specific day from the calendar instead of a day in the week.",
```

2024-08-20 23:13 UTC, alvinkim101 commented on resources/assets/uad_lists.json
> +    "description": "Used by the alarm clock to select a specific date from the calendar instead of a day of the week.",
I just removed the first sentence because it's redundant.

2024-08-22 12:08 UTC, AnonymousWP approved these changes

2024-08-22 12:08 UTC, AnonymousWP commented
Thanks for your contribution!

2024-08-22 12:09 UTC, merged