docs(CONTRIBUTING): recommend `rebase` from `main`
Universal-Debloater-Alliance/universal-android-debloater-next-generation pull request #597
Opened 2024-08-30 05:14 UTC by Rudxain

2024-08-30 06:56 UTC, AnonymousWP requested changes

2024-08-30 06:56 UTC, AnonymousWP commented on CONTRIBUTING.md
> +In short, there's one trunk branch named `main` (AKA `master`). Apart from `main`/`master` there can be different short-lived branches, such as:
I don't prefer abbreviations in the documentation. Surprisingly, there are still people who don't know what it means.

2024-08-30 06:56 UTC, AnonymousWP commented on CONTRIBUTING.md
> +**Don't**. Applying changes to/from arbitrary branches is a recipe for chaos. Even if it's absolutely necessary, whether to `merge` or `rebase` should be decided on a case-by-case basis.
```suggestion
**Don't** apply changes to/from arbitrary branches is a recipe for chaos. Even if it's absolutely necessary, whether to `merge` or `rebase` should be decided on a case-by-case basis.
```

2024-08-30 11:14 UTC, Rudxain commented on CONTRIBUTING.md
> +In short, there's one trunk branch named `main` (AKA `master`). Apart from `main`/`master` there can be different short-lived branches, such as:
What if we remove it altogether? 👀 IMO, the parentheses are self-explanatory

2024-08-30 22:50 UTC, Rudxain commented on CONTRIBUTING.md
> +**Don't apply changes to/from arbitrary branches**, that's a recipe for chaos! If you find yourself in a situation where it's absolutely necessary to sync, whether to `merge` or `rebase` should be de
Should we specify who decides? It implies "the UDA Org", but it may be taken as "the contributor can decide"

2024-08-31 09:07 UTC, AnonymousWP requested changes

2024-08-31 09:07 UTC, AnonymousWP commented on CONTRIBUTING.md
> +**Don't apply changes to/from arbitrary branches**, that's a recipe for chaos! If you encounter a situation where it's absolutely necessary to sync non-`main` branches, whether to `merge` or `rebase`
```suggestion
**Don't apply changes to/from arbitrary branches**, that's a recipe for chaos! If you encounter a situation where it's absolutely necessary to sync non-`main` branches, whether to `merge` or `rebase` should be decided by the UAD-ng org (with some contributor feedback) on a case-by-case basis.
```

2024-08-31 21:07 UTC, Rudxain commented on CONTRIBUTING.md
> +**Don't apply changes to/from arbitrary branches**, that's a recipe for chaos! If you encounter a situation where it's absolutely necessary to sync non-`main` branches, whether to `merge` or `rebase`
I meant "Universal Debloater Alliance organization". But, on second thought, the ones who should decide merge/rebase are this repo's team not the entire organization

2024-09-01 09:41 UTC, AnonymousWP commented on CONTRIBUTING.md
> +**Don't apply changes to/from arbitrary branches**, that's a recipe for chaos! If you encounter a situation where it's absolutely necessary to sync non-`main` branches, whether to `merge` or `rebase`
Yeah, and apart from that people would get confused like me. Thanks for the adjustment.

2024-09-01 09:41 UTC, AnonymousWP approved these changes

2024-09-01 09:41 UTC, merged