chore(bug_template): improve correctness, privacy, and comprehensiveness
Universal-Debloater-Alliance/universal-android-debloater-next-generation pull request #606
Opened 2024-09-05 06:32 UTC by Rudxain

2024-09-06 17:50 UTC, AnonymousWP requested changes

2024-09-06 17:50 UTC, AnonymousWP commented on .github/ISSUE_TEMPLATE/1-bug-report.yml
> +      - Windows # NT
I personally don't really see the relevance of this. Nobody runs Windows pre-NT. Maybe it's better to ask for the version instead. 😄

2024-09-07 05:25 UTC, Rudxain commented on .github/ISSUE_TEMPLATE/1-bug-report.yml
> +      - Windows # NT
I meant [the kernel](https://en.wikipedia.org/wiki/Windows_kernel) (also part of newer versions, including W11)

[MS is bad at naming](https://www.xda-developers.com/microsoft-remote-desktop-new-name) 💀

2024-09-07 11:28 UTC, AnonymousWP commented on .github/ISSUE_TEMPLATE/1-bug-report.yml
> +      - Windows # NT
Yeah I know you do, but it's better to mention OS version.

2024-09-07 21:33 UTC, Rudxain commented on .github/ISSUE_TEMPLATE/1-bug-report.yml
> +      - Windows # NT
I guess? But it's just a comment, users won't see it

2024-09-10 20:29 UTC, AnonymousWP approved these changes

2024-09-10 20:29 UTC, merged