pkg(motorola): add packages
Universal-Debloater-Alliance/universal-android-debloater-next-generation pull request #610
Opened 2024-09-06 19:37 UTC by Lost-Entrepreneur439

This closes #594

2024-09-10 23:58 UTC, AnonymousWP requested changes
Very-well documented, thanks for your PR.

2024-09-10 23:58 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "removal": "Recommended"
I doubt this should be part of the `Recommended` removal, as it's related to Wi-Fi management. `Expert` fits better in that case, I think.

2024-09-10 23:58 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "removal": "Advanced"
Is this a necessary package? I'm not familiar with this package, so I'm not sure in which `removal` it would fit, see: https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/wiki/FAQ

2024-09-10 23:58 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "description": "This package is involved in Motorola's setup process, particularly handling automatically generated resources related to the setup of the device.",
Won't removing this package cause issues after setting up the device?

2024-09-10 23:58 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "description": "This package is used during the Motorola device setup process, specifically for managing or presenting settings related to mobile data.",
Idem dito. Also because it presents settings related to mobile data.

2024-09-10 23:58 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "removal": "Advanced"
```suggestion
    "removal": "Expert"
```

2024-09-11 00:47 UTC, Lost-Entrepreneur439 commented on resources/assets/uad_lists.json
> +    "removal": "Recommended"
this was a copy and paste failure, yeah that was supposed to be expert

2024-09-11 05:00 UTC, schbrns commented on resources/assets/uad_lists.json
> +    "removal": "Recommended"
```suggestion
    "removal": "Expert"
```

2024-09-11 05:17 UTC, schbrns commented on resources/assets/uad_lists.json
> +    "description": "This package is associated with the user interface elements related to Wi-Fi management in Android.",
```suggestion
    "description": "Wi-Fi dialog. App to launch user dialogs requested by the Wi-Fi service is stored here. Contains the Activity the dialogs are launched from.\nhttps://source.android.com/docs/core/ota/modular-system/wifi\nhttps://android.googlesource.com/platform/packages/apps/Settings/+/refs/heads/main/src/com/android/settings/wifi/WifiDialog.java\nhttps://android.googlesource.com/platform/packages/apps/Settings/+/refs/heads/main/src/com/android/settings/wifi/WifiDialog2.kt",
```

2024-09-11 05:17 UTC, schbrns commented on resources/assets/uad_lists.json
> +    "removal": "Advanced"
```suggestion
    "removal": "Unsafe"
```

2024-09-11 05:25 UTC, schbrns commented on resources/assets/uad_lists.json
> +    "description": "This package is associated with the user interface elements related to Wi-Fi management in Android.",
Only first link is needed.

2024-09-11 05:27 UTC, schbrns commented on resources/assets/uad_lists.json
> +    "description": "This package contains resources related to Wi-Fi management, including string resources, images, and layout files used in the Wi-Fi settings and user interface.",
```suggestion
    "description": "Wi-Fi Service Resources. Overlay APK manifest is stored here. Extracts Wi-Fi configs.\nhttps://source.android.com/docs/core/ota/modular-system/wifi",
```

2024-09-11 05:31 UTC, schbrns commented on resources/assets/uad_lists.json
> +    "removal": "Advanced"
Likely has to do with an overlay prompting to install the partnered carrier app when eSIM is installed. retca = retail Canada. rectus = funny word.

2024-09-11 05:32 UTC, schbrns commented on resources/assets/uad_lists.json
> +    "description": "This package is part of Motorola's custom overlay for system settings, specifically tailored for the Motorola Edge 2024 (codename 'avatrn').",
I'm tired or I'd keep going. Satisfy my ADHD by getting rid of "This package is part of" from all of it. 💀

2024-09-11 05:36 UTC, schbrns commented on resources/assets/uad_lists.json
> +    "removal": "Recommended"
```suggestion
    "removal": "Advanced"
```

2024-09-11 05:39 UTC, schbrns commented on resources/assets/uad_lists.json
> +    "removal": "Advanced"
Expert?
Need to decide if 'systemui' and 'overlay' are consistently Expert or not.

2024-09-11 12:09 UTC, Lost-Entrepreneur439 commented on resources/assets/uad_lists.json
> +    "description": "This package handles the internal management of gesture-based navigation bars in the Android system UI.",
Change applied.

2024-09-11 12:19 UTC, Lost-Entrepreneur439 commented on resources/assets/uad_lists.json
> +    "removal": "Advanced"
that one would be expert, at first i thought it would've been advanced because it's not super important but yeah, it'd be better as expert.

2024-09-11 12:19 UTC, Lost-Entrepreneur439 commented on resources/assets/uad_lists.json
> +    "removal": "Advanced"
Not really, but I could imagine some people wanting it, I could change it to `Recommended` but it's not completely pointless and can't be easily reinstalled from Google Play, `Advanced` fits better in my opinion

2024-09-11 12:23 UTC, Lost-Entrepreneur439 commented on resources/assets/uad_lists.json
> +    "removal": "Recommended"
resolved in latest commit

2024-09-11 12:26 UTC, Lost-Entrepreneur439 commented on resources/assets/uad_lists.json
> +    "description": "This package is involved in Motorola's setup process, particularly handling automatically generated resources related to the setup of the device.",
yeah, you're correct, changed to expert

2024-09-11 12:26 UTC, Lost-Entrepreneur439 commented on resources/assets/uad_lists.json
> +    "removal": "Advanced"
solved in latest commit

2024-09-11 12:27 UTC, Lost-Entrepreneur439 commented on resources/assets/uad_lists.json
> +    "description": "This package is responsible for managing the transparency of the navigation bar in the Android system UI.",
everything you suggested has been added in the latest commit

2024-09-12 10:32 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "removal": "Advanced"
Then `Advanced` is good yeah, thanks.

2024-09-12 10:34 UTC, AnonymousWP requested changes

2024-09-12 10:34 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "description": "This package is part of Google Health Connect and is responsible for managing and controlling health-related data interactions.",
You forgot a `,` after `"`, which breaks the UAD list: https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/actions/runs/10811629949/job/29991441963?pr=610#step:6:277.

2024-09-13 01:58 UTC, schbrns commented
Didn't I change that one already?

2024-09-13 02:54 UTC, Lost-Entrepreneur439 commented on resources/assets/uad_lists.json
> +    "description": "This package is part of Google Health Connect and is responsible for managing and controlling health-related data interactions.",
> You forgot a `,` after `"`, which breaks the UAD list: https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/actions/runs/10811629949/job/29991441963?pr=610#step:6:277.

Fixed

2024-09-13 06:36 UTC, schbrns commented on resources/assets/uad_lists.json
> +    "description": "This package is part of Google Health Connect and is responsible for managing and controlling health-related data interactions.",
Lit. No time for commas over here.

2024-09-14 14:23 UTC, AnonymousWP requested changes
One more thing and then it should be ready to merge. 🙂

2024-09-14 14:23 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "description": "Health Connect by Android gives you a simple way to share data between your health, fitness, and wellbeing apps without compromising on privacy.\nOnce you've downloaded Health Con
```suggestion
    "description": "Health Connect by Android gives you a simple way to share data between your health, fitness, and wellbeing apps without compromising on privacy.\nOnce you've downloaded Health Connect, you can access it through your settings by going to Settings > Apps > Health Connect, or from your Quick Settings menu.\nhttps://play.google.com/store/apps/details?id=com.google.android.apps.healthdata",
```

You forgot about this.

2024-09-14 16:14 UTC, AnonymousWP approved these changes
Thanks for another contribution! 😁

2024-09-14 16:14 UTC, merged