build(Cargo): optimize `release` further
Universal-Debloater-Alliance/universal-android-debloater-next-generation pull request #626
Opened 2024-09-15 15:28 UTC by Rudxain

https://doc.rust-lang.org/cargo/reference/profiles.html

2024-09-15 15:32 UTC, Rudxain commented on Cargo.toml
> +strip = true
`strip` `true` is more consistent with `lto`

2024-09-15 15:33 UTC, Rudxain commented
Why is Cargo CI? 😕

2024-09-15 15:36 UTC, AnonymousWP commented
Because the `Cargo.toml` is used when building the assets, right? And assets are being build when a tag is pushed for a new version.🙂 Let me know if that way of thinking is incorrect.

2024-09-15 15:46 UTC, Rudxain commented
> `Cargo.toml` is used when building the assets

Correct. But Cargo is also used outside of CI, such as local environments.

I suppose we can keep it as "CI", as the [Wikipedia definition](https://en.wikipedia.org/wiki/Continuous_integration) seems to include build systems 🤔

2024-09-15 15:47 UTC, adhirajsinghchauhan requested changes

2024-09-15 15:47 UTC, adhirajsinghchauhan commented on Cargo.toml
> +codegen-units = 1
This is sure to lead to much slower code. IMO remove this line, it doesn't really help much with executable sizes, so let it be at the default of `16`.

2024-09-15 15:47 UTC, adhirajsinghchauhan commented on Cargo.toml
> +strip = true
Yes, `"symbols"` and `true` are the same thing, but it could change in future rust releases. I'm fine either way.

2024-09-15 15:49 UTC, adhirajsinghchauhan commented
I'm interested to see the size differences between panic `unwind` and `abort`. Could you post comparisons by building the latest release with both options?

2024-09-15 15:54 UTC, Rudxain commented on Cargo.toml
> +codegen-units = 1
I could only find this rust-lang/rust#47745 , but I'm not sure how to interpret all the linked issues 😕

Should we set it to 4 instead?

2024-09-15 16:03 UTC, adhirajsinghchauhan commented on Cargo.toml
> +codegen-units = 1
I believe that's specific to `lto="thin"`, which we don't use. We don't have any benchmarks for code performance, so the only test we can do is build with and without defaults codegen values, and compare file sizes.

2024-09-15 17:02 UTC, Rudxain commented
`cargo build --release; stat -c%s target/release/uad-ng` on 3 branches:
- `main` 16261816
- `build/opt-release` 14346792
- `default-codegen-units` (local) 14748040

2024-09-18 20:22 UTC, adhirajsinghchauhan approved these changes

2024-09-18 20:23 UTC, merged

2024-10-28 19:39 UTC, Rudxain commented
[This](https://github.com/rust-lang/cargo/issues/11298) is also worth referencing

2024-10-28 20:23 UTC, AnonymousWP commented
![image](https://github.com/user-attachments/assets/6343bab1-0fd9-42e7-9cb3-71ba63235cb6)

Perhaps we need to do this.

2024-10-28 22:11 UTC, Rudxain commented
@AnonymousWP wait! I meant "reference" as the thing I just did, which is "to mention it with a link". It's just to provide more info about the subject, as optimization is hard to get right (sometimes)