pkg(com.google.android.setupwizard): improve description
Universal-Debloater-Alliance/universal-android-debloater-next-generation pull request #637
Opened 2024-09-18 13:44 UTC by AnonymousWP

2024-09-18 13:53 UTC, Rudxain submitted a review, later dismissed

2024-09-18 13:59 UTC, Rudxain commented
It may be worth mentioning that the breakage only happens if there wasn't a Google account in "Accounts". That's why I could still sync, because I uninstalled SW after adding my account

2024-09-18 14:42 UTC, AnonymousWP commented
Better now?

2024-09-18 15:40 UTC, Rudxain requested changes

2024-09-18 15:40 UTC, Rudxain commented on resources/assets/uad_lists.json
> +    "description": "Android Setup\nThe factory reset device basic configuration setup guides you through the basics of setting up your device.\nWARNING: Oddly enough, disabling/uninstalling this pack
The wording is somewhat confusing 😕.  Something along the lines of "breaks syncing of newly-added Google accounts" or "breaks syncing of Google accounts setup after this pack is removed" would be better, IMO

2024-09-18 16:29 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "description": "Android Setup\nThe factory reset device basic configuration setup guides you through the basics of setting up your device.\nWARNING: Oddly enough, disabling/uninstalling this pack
Should be better now.

2024-09-19 08:06 UTC, Rudxain approved these changes

2024-09-19 08:34 UTC, merged