refactor: `sync` & `set_var`
Universal-Debloater-Alliance/universal-android-debloater-next-generation pull request #653
Opened 2024-09-24 22:13 UTC by Rudxain

- Store some strings as `const`s, [as explained here](https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/pull/620#issuecomment-2348630097)
- Since all calls to `set_var` specify `ANDROID_SERIAL` as key, I decided to define a function for it.

2024-09-25 05:23 UTC, adhirajsinghchauhan requested changes

2024-09-25 05:23 UTC, adhirajsinghchauhan commented on src/core/sync.rs
> +const PM_C: &str = "pm clear";
Use full words for both constants, to make it obvious what the string contains without needing to click through to the definition. They're not overly long anyway.

2024-11-26 08:41 UTC, Rudxain commented on src/core/sync.rs
> -                    env::set_var(ANDROID_SERIAL, &device[1]);
Now that I think about it, was this even necessary in the 1st place? `adb devices` doesn't need a serial, that's the whole point of the command (in this context). And the env-var is being replaced for every device in the loop, which implies only the last device will have a "useful" side-effect

2024-11-26 08:48 UTC, Rudxain commented on src/gui/mod.rs
> -                env::set_var(ANDROID_SERIAL, s_device.adb_id);
`selected_device` already "remembers", there's no need to mutate the env if we could simply do `adb -s SERIAL`

2024-11-26 08:51 UTC, Rudxain commented
[Why env-vars are unsafe](https://rachelbythebay.com/w/2017/01/30/env/)

2024-12-07 08:00 UTC, Rudxain commented on src/core/sync.rs
> -                    env::set_var(ANDROID_SERIAL, &device[1]);
I've just noticed that most `fn`s there "implicitly" run adb cmds. I might refactor this so that every `fn` requires an explicit serial

2024-12-14 13:24 UTC, Rudxain commented
Superseded by #757

2024-12-14 13:24 UTC, closed without merging