build(ci): Create new unit tests
Universal-Debloater-Alliance/universal-android-debloater-next-generation pull request #654
Opened 2024-09-25 19:24 UTC by Frigyes06

Created a few simple tests

2024-09-25 19:42 UTC, Frigyes06 commented
Why is macos not playing nice

2024-09-26 00:11 UTC, Rudxain commented
> macos not playing nice

_[Safari flashbacks 😭]_

In all seriousness, I assume it's a lack of file-system permissions

2024-09-26 00:17 UTC, Rudxain requested changes

2024-09-26 00:17 UTC, Rudxain commented on src/gui/style.rs
> +        assert_ne!(palette.base.foreground, Color::BLACK);
I think it would be wise to also check that FG and BG aren't similar colors, to guarantee high contrast

2024-09-27 22:24 UTC, Rudxain commented on src/gui/style.rs
> +        assert_ne!(palette.base.foreground, Color::BLACK);
For simplicity, just check that they aren't identical

2024-10-14 12:05 UTC, Rudxain commented
Thanks to everyone for your patience. I can finally review now

2024-10-14 12:09 UTC, Rudxain commented on src/core/config.rs
> +    fn create_default_config_file() {
We could expose this, as part of `Config `. But this is fine, for now

2024-10-14 12:21 UTC, Rudxain commented on src/gui/style.rs
> +        assert_ne!(palette.base.background, palette.base.foreground);
We should definitely add doc-comments explaining the intended usage of every `base`, `normal`, and `bright` colors (on another PR). I thought `foreground` was the text color 😅.

I had to search all references and check the `Theme` palettes to get a vague idea of which color corresponds to what 💀

FG & BG can be similar colors. My bad 😅

2024-11-04 01:14 UTC, merged