pkg(boyue): add Boyue packages
Universal-Debloater-Alliance/universal-android-debloater-next-generation pull request #699
Opened 2024-10-25 14:32 UTC by renanglr

This list of applications comes from a Boyue Likebook Mars e-book reader running Android 8.1 (OEM firmware version 3.1.1).

The descriptions should be accurate for all Boyue devices, however they have recently rebranded themselves as "Meebook" and their new devices are using applications which look identical to the ones used in the Boyue devices. I do not know if they changed the application IDs after rebranding.

2024-10-26 05:47 UTC, schbrns commented on resources/assets/uad_lists.json
> +    "removal": "Advanced"
```suggestion
    "removal": "Expert"
```

2024-10-26 05:49 UTC, schbrns approved these changes

2024-10-26 05:49 UTC, schbrns commented on resources/assets/uad_lists.json
> +    "removal": "Advanced"
```suggestion
    "removal": "Expert"
```

2024-10-27 04:18 UTC, schbrns commented on resources/assets/uad_lists.json
> +    "removal": "Advanced"
Removing the file manager breaks the functionality that allows you to manage your files. 🤔 
Same reason Camera would likely be expert.

2024-10-27 04:27 UTC, schbrns commented on resources/assets/uad_lists.json
> +    "removal": "Advanced"
Might need a change.

Modern Android features are not as independent as they used to be, and too tied together to be removing gallery/launcher/cloud/keyboard/browser/settings.

2024-10-27 12:00 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "removal": "Advanced"
> Might need a change.

As in we may want to change the Wiki or all removals of launchers?

2024-10-27 12:06 UTC, AnonymousWP requested changes
Requesting changes due to pending suggestions.

2024-10-27 20:41 UTC, schbrns commented on resources/assets/uad_lists.json
> +    "removal": "Advanced"
Yeah, I'm not going to argue with you about whether a file manager is core functionality or not. 
But for the sake of argument, what do you personally think cameras should be tagged as?

Your downloads example is irrelevant as you're point at the "ui" part of it which isn't needed for `com.android.providers.downloads`. 
```
  "com.android.providers.downloads": {
    "list": "Aosp",
    "description": "Downloads Manager\nProvider for downloaded files.\nContent providers encapsulate data, providing centralized management of data shared between apps.\nhttps://developer.android.com/guide/topics/providers/content-providers.html",
    "dependencies": [],
    "neededBy": [],
    "labels": [],
    "removal": "Unsafe"
  },
```

You don't **need** download manager to browse your downloads, but guess what you do need. A file manager.

OEM features, regardless of open source alternatives, are deeply rooted in the OS and will throw errors left and right if you start removing core functionality like a **file manager that is tied to the file system**.

2024-10-27 20:54 UTC, schbrns commented on resources/assets/uad_lists.json
> +    "removal": "Advanced"
> > Might need a change.
> 
> As in we may want to change the Wiki or all removals of launchers?

As in, we may want to change whatever is outdated in practise. I'll just quote what I said in the other comment.

> OEM features, regardless of open source alternatives, are deeply rooted in the OS and will throw errors left and right if you start removing core functionality like a **file manager that is tied to the file system**.

Cameras being advanced is pretty nuts too. 
It kills your facial recognition, document scanning, flashlight package, it messes with OEM Find My Device features, it messes with all sorts of apps that Google is putting out like `Circle to Search`. 

Even an OEM `Phone` package having a video calling feature, it is looking for the OEM `Camera` package.
OEM `Gallery` app? Photo editing? Cloud? Your Android flavour has a preference to look for its own packages and not third-party ones (obviously). 

It WILL look for them and it WILL cause temperature increases, RAM increases, CPU increases, and battery drain increases. As well as losing literal core and potentially SAFETY functionality.

2024-10-27 21:49 UTC, schbrns commented
Maintaining that the following should be Expert due to the contradictory nature of the package descriptions:

accountmanagement
>It is not clear which features depend on this, I presume it has something to do with syncing notes.
>Can be safely removed

byreader
>The launcher provides some useful features ... keep it even if you do not use the stock e-book reader app. (Plus, there are not many alternative launchers that are optimized for e-ink displays.)
>Can be safely removed, however

filemanager
>This package provides a file manager tweaked for e-ink usage.\nCan be safely removed.
Sounds weirdly deceptive. It's an OEM file manager, not a mod of one.

2024-10-28 04:52 UTC, schbrns commented
Right, it's always great to get information about new devices for the uad_lists, too. 

And it's totally fine that there isn't anything else online other than what you've found and tested yourself. My comment was more that, if there is any mystery about it, then it's Expert removal. 


If you can extract the APK, feed it into hybrid-analysis or the other APK one that looks cool, then there's more to look at. 

From here, it looks like Notes is a potential feature in accountmanagement, but given the name of it and what it actually looks like, it looks like it's the device's account management, literally. The invalid 400 error code is a mystery within a mystery.


I love using Obtainium and importing OSS apps through it too, but this needs to remain user-friendly. 

This is a black-and-white file manager that is designed for an e-ink display to save battery and allow it to do what it needs to do efficiently. 
Replacing it with a FOSS alternative that hasn't been updated in 1 year or a FOSS alternative that hasn't been updated in 5 years, seems like a lot of effort and a potential security flaw.
For something that already exists as part of the flavour, and seems pretty beneficial to be kept in this case, by design.

2024-10-28 18:11 UTC, schbrns commented
I tried to be nice and encouraging with the last one and even asked you to upload the APK (couldn't even manage that).

> I'll be honest, your complaints about replacing apps being a security risk makes no sense to me in this case. This is a device running Android 8 (with a security patch level of January 2019)

You provided two alternatives, one of which were last updated mid-2019. 🤣 

>Replacing the stock apps with FOSS alternatives is probably better for security.

This is what I'm getting at, FOSS or not, when they're **BOTH** 6 years old, the non-OEM is likely to be worse across the board.
And this isn't a regular file manager, it is a file manager that has been designed to save battery on e-ink devices.

Your git frustrations have nothing to do with my opinion regarding the removal list.

![image](https://github.com/user-attachments/assets/9b02dd2d-8381-4449-9dd6-07294e748361)
https://goodereader.com/blog/guides/boyue/Likebook-p78-manual.pdf

Since you didn't provide the APK upload, instead you can let us know what happens here in logcat when you tap the Accounts Management button. 
Does it crash the app?
Does it throw errors that may drain your battery or increase resource usage/temperature?

2024-10-28 19:27 UTC, closed without merging

2024-10-28 19:47 UTC, schbrns commented
> I think you're just talking past me at this point, I'm sorry, I won't be bothering anymore.

All good, you were having a tough time taking any constructive criticism.

Was it the Expert removal suggestion?
Was it asking you to upload the APK to a simple analysis website?
Was it when you tried to justify replacing a **niche** 6-year old OEM app with a 6-year old FOSS app?
Or, was it the manual that "didn't exist" that was the tipping point?

2024-10-28 20:21 UTC, AnonymousWP commented
This discussion has gotten way too much past the point, both of you. Instead of fighting it out (I understand both of you may get frustrated), would have been better to gather opinions from a third (or even fourth) user. This is also discouraging people to open PRs in the future perhaps.

2024-10-28 20:45 UTC, schbrns commented
Absolutely agreed. 
I'd like to clarify for anybody that reads this and feels discouraged by it, that there was no fighting, and there is no place for that in this repository.

It occasionally occurs that for more unknown devices, without an online presence, we may request additional assistance from you.

The request for additional assistance may occasionally look like this:

- > Right, it's always great to get information about new devices for the uad_lists, too.
- > And it's totally fine that there isn't anything else online other than what you've found and tested yourself. My comment was more that, if there is any mystery about it, then it's Expert removal.
- > If you can extract the APK, feed it into hybrid-analysis or the other APK one that looks cool, then there's more to look at.

How not to reply to the requested additional assistance to improve the project with your contribution:
> I'll be honest, your complaints [...] make[s] no sense to me in this case

How not to follow-up:
- Don't impulsively delete your fork because somebody wants to discuss whether your requested change belongs in one list or another.