Added com.taboola.scoop (Wallpaper Carousel)
Universal-Debloater-Alliance/universal-android-debloater-next-generation pull request #714
Opened 2024-11-10 12:35 UTC by Unchanged4352

Added com.taboola.scoop (Wallpaper Carousel)

2024-11-11 15:17 UTC, AnonymousWP requested changes

2024-11-11 15:17 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +
Please remove this line, the pipeline is failing: https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/actions/runs/11765171736/job/32771550514?pr=714

2024-11-11 15:17 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "description": "Random wallpaper on lock screen (as i saw it personalizes it too), you need to open this app to make it work and when you swipe from right to left with your hand, it opens a menu
```suggestion
    "description": "Random wallpaper on lock screen (as i saw it personalizes it too). You need to open this app to make it work and when you swipe from right to left, it opens a menu on the right where random news appears.",
```

2024-11-13 23:22 UTC, AnonymousWP approved these changes
Thanks.🙂

2024-11-13 23:22 UTC, merged

2024-11-14 03:43 UTC, Unchanged4352 commented
> Thanks.🙂 

Np 🙂