build(ci): fix macOS linting failing
Universal-Debloater-Alliance/universal-android-debloater-next-generation pull request #730
Opened 2024-11-23 19:14 UTC by AnonymousWP

Looks like for MacOS we need to allow `bright.surface` to be black. This seems to have fixed it.

2024-11-25 05:15 UTC, Rudxain commented on src/gui/style.rs
> +    if palette.bright.surface != Color::BLACK {
This gave me an [idea for a lint](https://github.com/rust-lang/rust-clippy/issues/13725), so the code was helpful, in some sense :sweat_smile:. Thanks for trying anyways!

2024-11-25 05:18 UTC, Rudxain requested changes

2024-11-25 05:18 UTC, Rudxain commented on src/gui/style.rs
>          assert_ne!(palette.bright.surface, Color::BLACK);
This is a dupe, so we should remove the entire `if` with its body

2024-11-25 05:22 UTC, Rudxain commented on src/gui/style.rs
>          assert_ne!(palette.bright.surface, Color::BLACK);
Although I find it quite odd that a specific color "fixes" MacOS CI, why not the others?

2024-11-25 21:40 UTC, AnonymousWP commented on src/gui/style.rs
> +    if palette.bright.surface != Color::BLACK {
🙂

2024-11-25 21:43 UTC, AnonymousWP commented on src/gui/style.rs
>          assert_ne!(palette.bright.surface, Color::BLACK);
> This is a dupe, so we should remove the entire if with its body

Where do you see a second variant of `palette.bright.surface`? I don't see it.🤔Wouldn't that break the CI again?

> Although I find it quite odd that a specific color "fixes" MacOS CI, why not the others?

Could be that a new MacOS Runner update is out and that now MacOS handles it differently? Or am I saying something very stupid now?😅

2024-11-26 09:04 UTC, Rudxain commented on src/gui/style.rs
>          assert_ne!(palette.bright.surface, Color::BLACK);
> Where do you see a second variant of `palette.bright.surface`? I don't see it.🤔Wouldn't that break the CI again?

I'm not sure if this is a GH bug, or if I misread something, but the code
```rust
if palette.bright.surface != Color::BLACK {
        assert_ne!(palette.bright.surface, Color::BLACK);
}
```
Is asserting a condition that has already been checked:
"If surface isn't black, ensure that it isn't black"

> Could be that a new MacOS Runner update is out and that now MacOS handles it differently?

That's a possibility! But I was thinking that maybe the test only runs if it's inside a test module, which seems paradoxical considering the `#[cfg(test)]` is literally conditional-compilation (which implies it shouldn't have ran in the 1st place, assuming something was wrong with the runner)

2024-11-26 22:27 UTC, AnonymousWP commented on src/gui/style.rs
>          assert_ne!(palette.bright.surface, Color::BLACK);
Where else is that checked? What do you want me to do now exactly? I'm a bit lost.😅

2024-11-28 20:47 UTC, Rudxain commented on src/gui/style.rs
>          assert_ne!(palette.bright.surface, Color::BLACK);
https://doc.rust-lang.org/std/macro.assert_ne.html

Assertions `panic` if the condition is `false`. It'll never `panic` because that `if` already guarantees the condition is always `true`.

The only way the assertion could `panic` is if there was a 2nd thread mutating the `struct` (via raw pointers) **immediately after the `if` but immediately before the assertion**, which is an extremely precise timing!

2024-12-08 02:40 UTC, Rudxain commented
I KNOW WHY IT FAILS. Look at this:
```
assertion `left != right` failed
  left: Color { r: 0.0, g: 0.0, b: 0.0, a: 1.0 }
 right: Color { r: 0.0, g: 0.0, b: 0.0, a: 1.0 }
```
Floating-point quirks strikes again! It seems the macOS runner uses a different implementation of FP comparison. We need to change the assertion to test _approximate_ identity, not _exact_ identity

2024-12-08 03:01 UTC, Rudxain commented
Since AWP is taking some time because of personal reasons (they explained it in a Discord channel), I'll commit the changes. I'm announcing this in advance, to prevent merge-conflicts

2024-12-08 03:30 UTC, Rudxain commented
I misread. It's `!=` not `==`. So the assertion is fine, but the palette is somehow totally incorrect???

2024-12-08 03:52 UTC, Rudxain commented
https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/blob/25dfa8b0755f3c9b0900eb0fc4364c7192b8ead0/src/core/theme.rs#L104

That's the only palette field that's pure black. It's part of the `LIGHT` color-scheme. According to [this](https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/issues/627#issuecomment-2361817586), this implies the macOS theme is `Light` by default (or cannot be detected).

So we have 3 (or more?) options:
- Modify the `LIGHT` theme such that the field is no longer black
- Don't rely on `Theme::default()` and use `Theme::Dark` explicitly
- Delete/comment-out that one problematic assertion

2024-12-08 04:00 UTC, Rudxain approved these changes

2024-12-08 04:01 UTC, merged

2024-12-08 12:14 UTC, Rudxain commented
I forgot to request review from @Frigyes06 :sweat_smile: