pkg(xaomi/google): add various apps
Universal-Debloater-Alliance/universal-android-debloater-next-generation pull request #733
Opened 2024-11-25 02:13 UTC by schbrns

2024-11-25 03:21 UTC, Rudxain requested changes

2024-11-25 03:21 UTC, Rudxain commented on resources/assets/uad_lists.json
> -    "description": "Google Search box (https://play.google.com/store/apps/details?id=com.google.android.googlequicksearchbox)\nRuns in the background.\nPointless. If you need a shortcut to Google on
While I agree with removing redundancy, this goes a bit too far. Some of the info here could be helpful!

2024-11-25 03:21 UTC, Rudxain commented on resources/assets/uad_lists.json
> +    "description": "Google app (https://play.google.com/store/apps/details?id=com.google.android.googlequicksearchbox)\nFind quick answers, explore your interests, and stay up to date with Discover."
I like the conciseness here, but it's missing [this](https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/issues/688#issuecomment-2411307458), which Google has poorly documented (unless I'm missing something?)

2024-11-25 03:22 UTC, Rudxain commented on resources/assets/uad_lists.json
> +    "description": "Mi File Manager\nFind files faster, manage files easily, and share them offline with others. Supports: quick search, moving, deleting, opening, and sharing files, as well as renam
Very comprehensive!

2024-11-25 03:22 UTC, Rudxain requested changes

2024-11-25 03:22 UTC, Rudxain commented on resources/assets/uad_lists.json
> +    "description": "Mi File Manager\nFind files faster, manage files easily, and share them offline with others. Supports: quick search, moving, deleting, opening, and sharing files, as well as renam
```suggestion
    "description": "Mi File Manager\nFind files faster, manage files easily, and share them offline with others. Supports: quick search, moving, deleting, opening, and sharing files, as well as renaming, unzipping, and copy-paste. Mi File Manager also recognizes multiple file formats, including music, videos, images, documents, APKs, and zip-files. We update our app regularly to bring you the best experience\nKey Features:\nRecent, Categories, Storage, Cleaner, Mi Drop, Global search, Multiple file formats support, File compression, Manage multiple filers, Multiple languages supported.",
```

2024-11-25 06:44 UTC, schbrns commented on resources/assets/uad_lists.json
> +    "description": "Mi File Manager\nFind files faster, manage files easily, and share them offline with others. Supports: quick search, moving, deleting, opening, and sharing files, as well as renam
Gotta love that those typos were grom the GPlay listing.

2024-11-25 07:20 UTC, Rudxain commented on resources/assets/uad_lists.json
> +    "description": "Google app (https://play.google.com/store/apps/details?id=com.google.android.googlequicksearchbox)\nFind quick answers, explore your interests, and stay up to date with Discover."
> legacy versions not supporting voice typing.

Yep. IIRC, the legacy behavior was that only the Google app could provide "official" VTT, but then they defined an open (AOSP) API where any app could register itself as a VTT handler. I have no source for that, it's just speculation about what happened "behind the scenes" :thinking:

However, I've found a [source for the history of the feature](https://9to5google.com/2021/04/29/android-12-google-voice-typing/)

> Does Gboard's voice typing work?

I'll have to confirm with the Galaxy J3 Mission (Android 8). I remember it also depended on G-App.

> Can you confirm that it **breaks** Lens?

I _kinda_ remember installing Lens with GApp disabled, and it complaining that it needs GApp. Same for G-Assistant.

Maybe the dependencies have changed? Needs testing.

> Google app as an all-in-one app for a bunch of apps

[WeChat](https://en.wikipedia.org/wiki/WeChat) moment, lol

> I've tried standalone Gemini and Lens, and both have worked without Google app (might be wrong about Gemini).

Interesting :eyes:

2024-11-25 07:23 UTC, Rudxain commented on resources/assets/uad_lists.json
> +    "description": "Google app (https://play.google.com/store/apps/details?id=com.google.android.googlequicksearchbox)\nFind quick answers, explore your interests, and stay up to date with Discover."
> `com.google.android.tts`

They renamed "Speech Services" yet again :skull:

2024-11-25 07:24 UTC, schbrns commented on resources/assets/uad_lists.json
> +    "description": "Google app (https://play.google.com/store/apps/details?id=com.google.android.googlequicksearchbox)\nFind quick answers, explore your interests, and stay up to date with Discover."
That's fair, I suspect that much. Either it complains or it does nothing because it fails to call the Google app activity.

2024-11-25 07:26 UTC, schbrns commented on resources/assets/uad_lists.json
> +    "description": "Google app (https://play.google.com/store/apps/details?id=com.google.android.googlequicksearchbox)\nFind quick answers, explore your interests, and stay up to date with Discover."
```suggestion
    "description": "Google app (https://play.google.com/store/apps/details?id=com.google.android.googlequicksearchbox)\nNOTE: Google Assistant, Gemini, Lens, and TTS (Speech Recognition & Synthesis) are dependent on the Google app.\nFind quick answers, explore your interests, and stay up to date with Discover.",
```

2024-11-25 07:36 UTC, Rudxain commented on resources/assets/uad_lists.json
> +    "description": "Google app (https://play.google.com/store/apps/details?id=com.google.android.googlequicksearchbox)\nFind quick answers, explore your interests, and stay up to date with Discover."
That's mostly correct (I haven't tested, yet). But I don't remember Google TTS depending on the G-App. What I meant is the voice-typing input-method

2024-11-29 00:03 UTC, Rudxain commented on resources/assets/uad_lists.json
> +    "description": "Google app (https://play.google.com/store/apps/details?id=com.google.android.googlequicksearchbox)\nFind quick answers, explore your interests, and stay up to date with Discover."
> I think TTS and voice typing input method are the same package? Starting to forget.

Nowadays, yes. "Speech Services" provides both. But in "ye olden days", it was just TTS (the package name is a vestige of that)

2025-01-07 13:56 UTC, AnonymousWP commented
@schbrns Could you please follow-up on this? 😁

2025-02-02 20:48 UTC, closed without merging

2025-02-02 20:48 UTC, AnonymousWP commented
Closing as @schbrns will follow it up in a new PR.