pkg(samsung): Add packages
Universal-Debloater-Alliance/universal-android-debloater-next-generation pull request #743
Opened 2024-11-26 02:37 UTC by YoshiiShell

Add the packages:
com.samsung.android.callassistant
com.monotype.android.font.roboto
com.samsung.slsi.telephony.silentlogging
com.google.android.photopicker

2024-11-26 08:51 UTC, AnonymousWP commented
@YoshiiShell You can just push new commits to this branch/PR, no need to open a new one.

2024-11-26 08:59 UTC, AnonymousWP commented
Another error:

```
thread 'core::uad_lists::tests::test_parse_json' panicked at src/core/uad_lists.rs:243:60:
Unable to parse: Error("expected `,` or `}`", line: 10567, column: 3)
```

2024-11-26 11:34 UTC, schbrns commented
Thanks, I'll review this tomorrow. Need to check my One UI file so I can merge mine in too.

2024-11-26 12:10 UTC, schbrns commented
@YoshiiShell If you have time, could you submit Google as one PR and font (should be Aosp) as another? This PR's pkg scope is samsung. Thanks.

2024-12-17 15:23 UTC, AnonymousWP requested changes
Sorry for coming back to you so late.

2025-01-07 13:57 UTC, AnonymousWP commented
@YoshiiShell Could you please follow-up on this so we can merge it?

2025-02-02 19:39 UTC, AnonymousWP commented
@YoshiiShell 👀

2025-02-05 23:24 UTC, schbrns commented on resources/assets/uad_lists.json
> +   "removal": "Recommended"
```suggestion
   "removal": "Expert"
```
For the reason @AnonymousWP posted above, combined with Galaxy AI breakage in One UI 6.1+.

2025-02-05 23:32 UTC, schbrns requested changes
Changed removal to Expert.

2025-02-05 23:33 UTC, schbrns approved these changes

2025-02-05 23:34 UTC, schbrns commented on resources/assets/uad_lists.json
> +  "com.samsung.android.callassistant":{
```suggestion
  "com.samsung.android.callassistant": {
```

2025-02-05 23:34 UTC, schbrns commented on resources/assets/uad_lists.json
> +  "com.samsung.slsi.telephony.silentlogging":{
```suggestion
  "com.samsung.slsi.telephony.silentlogging": {
```

2025-02-05 23:35 UTC, schbrns requested changes
Formatting.

2025-02-05 23:35 UTC, schbrns approved these changes

2025-02-06 23:45 UTC, schbrns commented
I'm going to PR the formatter to main branch, this is silly. 
We're working with a monolithic JSON file, we should never need to worry about manual formatting.

2025-03-19 10:25 UTC, AnonymousWP commented
@YoshiiShell

2025-03-22 10:46 UTC, AnonymousWP commented
Merging with new commit due to radiosilence.

2025-03-22 10:47 UTC, AnonymousWP approved these changes

2025-03-22 10:50 UTC, merged