Refactor/adb api
Universal-Debloater-Alliance/universal-android-debloater-next-generation pull request #757
Opened 2024-12-14 13:14 UTC by Rudxain

- Follow up of #653
- See https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/pull/653#issuecomment-2526000435

2024-12-16 19:29 UTC, adhirajsinghchauhan requested changes
Overall, there's only one or two good changes here (e.g. explicit serial, deduping `android_sdk >= 21`). Most of the other ones are subjective, so they may not be beneficial to others. It is my opinion that changes for the sake of changes should not be done.

I am not a fan of shortening variable names, as none of them were long enough that they needed abbreviation in the first place. For example, command => cmd, packages => packs, shell => sh is wholly unnecessary and adds noise to this PR.  It's also not done consistently, as sometimes we see the full word being used (packages), and in other places two different short-forms. (e.g. packs and pack)

Even the renaming of `Phone` to `Device` was not necessary, especially when considering it's unrelated to this PR, and that some variables are named `device`, some `dev`, and some remain as `phone`.

Forgive the bluntness, but please revert any such subjective changes. We can discuss the specifics on Discord.

Typing in natural language form is more efficient for the developer. When we think of typing "command", we expect to start typing it and have autocomplete suggest it as-is. It will not surface "cmd", so we'd need to remember to type abbreviations everywhere, only to realise that abbreviations are not consistently used. This extra step is at odds with the basic methodology of good, clean code for everyone.

2024-12-16 21:23 UTC, Rudxain commented on src/gui/views/settings.rs
> +                            multi_user_mode: supports_multi_user(phone),
Yep, I [noticed some inconsistencies](https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/issues/614#issuecomment-2525089684), so I tried to find docs about which API level should be checked, and I defaulted to Android 5.0

2024-12-16 22:02 UTC, Rudxain commented
> Most of the other ones are subjective, so they may not be beneficial to others. It is my opinion that changes for the sake of changes should not be done.

I agree with the sentiment, as major refactors could introduce bugs. I tried my best to document all possible places where I could've created one.

> I am not a fan of shortening variable names, as none of them were long enough that they needed abbreviation in the first place. For example, command => cmd, packages => packs, shell => sh is wholly unnecessary and adds noise to this PR

yeah :sweat_smile:, I'll revert that.

> Even the renaming of `Phone` to `Device` was not necessary, especially when considering it's unrelated to this PR, and that some variables are named `device`, some `dev`, and some remain as `phone`.

I'll revert the rename and defer that to its own PR. I did too much "opportunistic refactoring" (mostly just "opportunistic renaming", which is not very valuable)

> Forgive the bluntness, but please revert any such subjective changes. We can discuss the specifics on Discord.

Ok :sweat_smile: :slightly_frowning_face:, I'll try to revert all out-of-scope changes. I can't do it today. I'll have more time on the weekend.

> at odds with the basic methodology of good, clean code for everyone.

Agreed. One of the motivations I had in mind for this PR is to make the code-base more accessible to newcomers (#731), but the context-sensitive variable names might go against that goal

2024-12-16 22:20 UTC, Rudxain commented on src/core/sync.rs
> +pub enum PmLsPackFlag {
> we should use full, descriptive names

I agree. Single-letter is bad. And it even looks ugly because of the relative length asymmetry with the `enum` name.

I tried to mirror the ADB CLI, but I've _already deviated_ from it when I renamed `list_users` to `ls_users`, so I guess it doesn't hurt to improve the flag names.

> For completeness, we could also add entries for all other possible flags (f, d, s, 3, i) ([docs](https://developer.android.com/tools/adb#pm)).

`3` and `s` should probably be on a distinct `enum`, as they are a different kind of filter. Same for `i` and `f`.

About completeness, what about `#[non_exhaustive]` :eyes: ? That way, we can easily add the other flags if we need them

2024-12-26 22:40 UTC, Rudxain commented
This week, I've been busier than I expected, so I couldn't work on this

2025-01-23 23:03 UTC, AnonymousWP commented
For which milestone do we target this by the way? Because it's a pretty big refactor.

2025-01-24 01:53 UTC, Rudxain commented on src/core/adb.rs
> +    pub fn list_packages_sys(
I'm concerned about this: #592. What if want to use a [flag other than `-s`](https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/pull/757#discussion_r1887346099)?

Should I add the parameter now, or should we wait until we need it?

2025-01-24 02:17 UTC, Rudxain commented
Some parts of the code-base still need to be migrated to the new API, but I decided to stop here, as the diff is already big (and I'm kinda burnt out :skull:). Further refactoring should happen on future PRs

2025-01-24 02:21 UTC, Rudxain commented
> For which milestone do we target this by the way? Because it's a pretty big refactor.

(I didn't see that comment until now)

The current one, I guess :thinking:

2025-01-24 03:25 UTC, Rudxain commented
After adding an unconditional `info` logger to the new API, I've found something interesting:

```
INFO  [src/gui/views/list.rs:157] -----------------------------------------------------------------
INFO  [src/gui/views/list.rs:158] ANDROID_SDK: 0 | DEVICE: fetching devices...
INFO  [src/gui/views/list.rs:162] -----------------------------------------------------------------
ERROR [src/gui/views/list.rs:877] AppsView ready but no phone found
INFO  [src/core/adb.rs:120] Ran command: adb 'shell' 'pm' 'list' 'packages' '-s' '-u'
INFO  [src/core/adb.rs:120] Ran command: adb 'shell' 'pm' 'list' 'packages' '-s' '-e'
INFO  [src/core/adb.rs:120] Ran command: adb 'shell' 'pm' 'list' 'packages' '-s' '-d'
```

This implies `fetch_packages` is being called even if there's no device (sub-optimal):
https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/blob/0238982a53dc5cf2f460f00487eb940264793c7c/src/core/utils.rs#L39-L59

This also seems to happen on `main` too:
https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/blob/bfda7d0a8e8eb3d473085afe06b220a8e26a4021/src/gui/views/list.rs#L854-L856
https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/blob/bfda7d0a8e8eb3d473085afe06b220a8e26a4021/src/gui/views/list.rs#L159-L177

2025-01-24 03:37 UTC, Rudxain commented on src/core/adb.rs
> +                    dev_stat[(tab_idx + 1)..].to_string(),
I've found info on `adb help`:
```
scripting:
 wait-for[-TRANSPORT]-STATE...
     wait for device to be in a given state
     STATE: device, recovery, rescue, sideload, bootloader, or disconnect
     TRANSPORT: usb, local, or any [default=any]
```
So now we know the full list of states, which we can turn into a (`non_exhaustive`) enum!

As a bonus, `wait-for-device` allows UAD-NG to stop polling `adb devices` (no need for `retry`!)

2025-01-29 02:05 UTC, Rudxain commented
I just realized a minor performance oversight: It's possible to "batch" multiple `adb shell` commands in one call, but this API makes batching impossible. An easy fix would be to not implicitly `run` commands, and allow "finished" shell commands to become `ShellCommand` objects for every built argument-list, with an implicit ";" in between each finished command.

So instead of:
```sh
adb shell pm uninstall --user 0 a.a
adb shell pm uninstall --user 0 b.b
```
It would be:
```sh
adb shell 'pm uninstall --user 0 a.a; pm uninstall --user 0 b.b'
```

This guarantees `adb` and `mksh` are executed only once, even when changing the states of thousands of packs.

The biggest obstacle to this, are commands whose output must be parsed: Batching `pm list` commands would actually be slower, as we would need to iterate over every pack, trying to find the boundaries between the outputs of distinct flags:

```sh
# ambiguity!
adb shell 'pm list packages -e; pm list packages -d'
```

A solution is to add a delimiter between outputs:
```sh
adb shell '\
pm list packages -e; \
echo\
pm list packages -d\
'
```
Now we simply `split` by "\n", and we've efficiently resolved the ambiguity!

IMO, we shouldn't worry too much about this. It's needlessly complicated just to improve performance

2025-02-07 07:21 UTC, Frigyes06 approved these changes

2025-02-07 07:23 UTC, Frigyes06 commented on src/core/adb.rs
> +    pub fn list_packages_sys(
For now I don't think it's necessary.

2025-02-07 10:31 UTC, Rudxain commented
This will cause a merge-conflict with #808. I'm going to merge this before #808, for the following reasons:
- This PR is much older
- It solves instability issues caused by `env` vars
- It seems easier to solve merge-conflicts on a smaller PR

2025-02-07 10:44 UTC, merged

2025-02-08 02:05 UTC, Rudxain commented
I forgot to emphasize this, but we have to **test the multi-user** handling before release. I'm not confident that `adb::list_users` or `sync::list_users_parsed` work 100% properly. I don't have devices with multiple users, so I would have to install an emulator or something

2025-02-10 21:41 UTC, AnonymousWP commented
Hey @Rudxain, just wanted to thank you for your tremendous work on this PR, it was probably a lot of work. Feel free to convert one of your comments into an issue that are deemed important enough.

Could someone test this? I don't have multiple users either. Perhaps create an issue and add it to the 1.1.1 milestone.