Rewording for miui.systemui.plugin
Universal-Debloater-Alliance/universal-android-debloater-next-generation pull request #759
Opened 2024-12-16 04:23 UTC by cameronj86

HyperOS devices are now the default for Xiaomi, so the impact of removal should focus on the impact re: HyperOS first (losing Quick Settings) and the impact re: MIUI second (gaining AOSP-style volume GUI).

2024-12-17 19:58 UTC, AnonymousWP requested changes
Thanks for your contribution. 🙂

2024-12-17 19:58 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "description": "System UI Plug-in. If using HyperOS, when removed this breaks the iOS-style quick settings and Android will use the AOSP-version of the volume bar & reboot screen (AKA the option
```suggestion
    "description": "System UI Plug-in. When using HyperOS, removing this package breaks the iOS-style quick settings and Android will use the AOSP-version of the volume bar & reboot screen (AKA the option to power off/reboot your device). If your device is using MIUI, only the volume bar will change.",
```

2024-12-18 11:40 UTC, AnonymousWP commented
You seem to only have merged main to this branch. If you commit the suggestion (you'll have to do it manually), I'll approve & merge.

2024-12-23 05:13 UTC, cameronj86 commented
Whoops. My second PR ever. I will sort it out this week.

2025-01-07 13:57 UTC, AnonymousWP commented
> Whoops. My second PR ever. I will sort it out this week.

👀

2025-02-05 23:41 UTC, schbrns submitted a review, later dismissed

2025-02-06 00:20 UTC, cameronj86 commented
Sorry, got spooked when the required steps veered into uncharted git/GitHub territory and the next steps weren't working for me 😅

I tried to merge through the Github UI and got confused. Please let me know if the same steps still apply re: commit & push or if I need to do new steps now

2025-02-06 11:31 UTC, AnonymousWP commented
> Sorry, got spooked when the required steps veered into uncharted git/GitHub territory and the next steps weren't working for me 😅
> 
> I tried to merge through the Github UI and got confused. Please let me know if the same steps still apply re: commit & push or if I need to do new steps now

You again just merged main into your own branch. You'll just have to copy the text I suggested (description field) manually and paste it within your own branch, then push.

2025-02-06 23:31 UTC, schbrns commented
> > Sorry, got spooked when the required steps veered into uncharted git/GitHub territory and the next steps weren't working for me 😅
> > I tried to merge through the Github UI and got confused. Please let me know if the same steps still apply re: commit & push or if I need to do new steps now
> 
> You again just merged main into your own branch. You'll just have to copy the text I suggested (description field) manually and paste it within your own branch, then push.

This is exactly why I approved it. At this point it would be easier for the contributor to just re-sync their fork after we manually add these packages. There is a TON of overhead being asked of contributors.

2025-02-13 00:36 UTC, cameronj86 commented
Ack! this is a shit-show on my end. I did a few things wrong in my working dir  so I'm going to reset and try again. Thanks for your patience through all this

2025-03-17 20:35 UTC, schbrns submitted a review, later dismissed

2025-03-19 09:35 UTC, AnonymousWP commented
@schbrns Please do not approve changes while another team member _requested_ changes.

2025-03-22 10:54 UTC, AnonymousWP approved these changes

2025-03-22 10:58 UTC, merged